### ISSUE TITLE
如何使用 Toggl：《活在当下：在时间的陪伴下向着目标持续前进着》

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#103]
## Description

- What's Target？
  - 输出一篇博客文章
  - 各种小 Tips

## References

- #85 记录时间这件小事儿

## Efforts

- [New scenario | Integromat](https://www.integromat.com/scenario/6555/edit)
- [Edit Step - Zapier](https://zapier.com/app/editor/15523121/overview)

**Comment by JimmyLv** [comment]
时间分类还是很蛋疼啊

**Comment by linesh-simplicity** [comment]
没啥蛋疼的呀，做这种事只要抱着一种开始了就超过80%的人的心态，觉得一切都变得轻松了…

**Comment by JimmyLv** [comment]
在[《搞定》最佳实践：如何利用滴答清单（TickTick）实践 GTD 理念？ | 吕立青的博客](https://blog.jimmylv.info/2017-02-20-gtd-best-practice-137/)中找到了答案：

只有足够「项目」size 的任务才可以被纳入 GitHub Issues，从而使得 TickTick 能够完美地与之前的敏捷学习系统相结合，这是我最开心的地方，而且让我找到了 **番茄工作法** 和 **Toggl 计时** 在整个流程中的位置，即 **专注当下** 与 **辅助回顾**。

**Comment by JimmyLv** [comment]
做最重要的事情。
