### ISSUE TITLE
《区块链将如何重新定义世界》

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#109]
共计379页

2.35 hours 读了前 155 页，平均 66页/hour

大概还需 3.5 hours

**Comment by kbyyd24** [comment]
66页/hour :scream: 

怎么做到?

**Comment by JimmyLv** [comment]
@kbyyd24 啊哈哈哈，手机上的页数

**Comment by kbyyd24** [comment]
@JimmyLv 那也挺快的

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/21339534/0d968bac-c6bb-11e6-9c4e-042080f188ba.png)
