### ISSUE TITLE
个人成长基础设施之硬件&软件篇

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#121]
## 硬件篇

- MacBook Pro 15‘ 💻
- iPhone 6s Plus 📱
- （蓝牙）耳机 🎧 & 音响 :sound:
- 机械键盘 HHKB ⌨️

### level 0. command line

- [iTerm2](https://www.iterm2.com/downloads.html) · 最强 Terminal、组合键、History
- [Homebrew](http://brew.sh/) & [Homebrew Cask](https://caskroom.github.io/) & [Cakebrew](https://www.cakebrew.com/) GUI · 装软件的正确姿势
- [Oh My Zsh](http://ohmyz.sh/) & alais & autocomplete · 最强 bash、自定义、自动补全、语法高亮
- [nvm](https://github.com/creationix/nvm) · JSer 管理 Node 版本的正确姿势
- [cnpm](https://github.com/cnpm/cnpm) & [Yarn](https://yarnpkg.com/) & npm packages manager (inside Intellij or ndm GUI or npm-check-updates) · Node 下 NPM 包管理及其升级（为了速度、可视化...）
- [Jekyll](https://jekyllrb.com/) or [Hexo](https://hexo.io/) · 博客相关
- of course learning linux bash first

### level 1. GUI Applications

- [Alfred](https://www.alfredapp.com/help/getting-started/cheatsheet/) & Workflows #78 · 万能单一入口「Less is more, 简约而不简单」
- [Chrome](https://www.google.com/intl/en/chrome/browser/desktop/) & Extensions #140 · 无敌 Browser
- [Sublime Text](https://www.sublimetext.com/3) & [Package Control](https://packagecontrol.io/installation) & Packages #142 · 无敌 Editor
- [IntelliJ IDEA](https://www.jetbrains.com/idea/) & Plugins #143 · 无敌 IDE
- [Dash](https://kapeli.com/dash) · 查文档必备
- [Shortcat](http://support.shortcatapp.com/kb/general/getting-started) · 全键盘操作
- [Amphetamine](https://itunes.apple.com/app/amphetamine/id937984704?mt=12) · 类似 caffeine but 更好用更好看
- [XX-net](https://github.com/XX-net/XX-Net) · 翻墙必备（当 VPN 抽风…）
- [smcFanControl](https://www.eidac.de/?cat=40) · 风扇控制，夏日解暑/冬日取暖 必备
- [iStat for Mac](https://bjango.com/mac/istat/) · 参数控（隐藏以弱化该功能）
- [ShiftIt](https://github.com/fikovnik/ShiftIt) · 窗口布局神器（开源）
- [Snap](https://itunes.apple.com/eN/app/snap/id418073146?mt=12) · Option + Nums 快速切换常用 Apps
- [Bartender 2](https://www.macbartender.com/) · 隐藏菜单栏图标（拯救性 App… 防止注意力干扰…）
- [RescueTime](https://www.rescuetime.com/dashboard?src=client) · 记录 Apps 使用时间
- [Karabiner](https://github.com/tekezo/Karabiner) · 改键神器（开源）
- [KeyCastr](https://github.com/keycastr/keycastr) · 按键显示
- [截图(Jietu)](https://itunes.apple.com/cn/app/jie-tu-jietu-kuai-su-biao/id1059334054?mt=12) · 腾讯出品
- [快贴](http://clipber.com/clipber/?rnd=0.34849009985173485) · 类 Pin，免费（macOS 的 universal clipper 简直不能用…）
- [Markoff](https://github.com/thoughtbot/Markoff) · 预览 Markdown 内容（查看 > 编辑）
- [搜狗输入法](http://pinyin.sogou.com/mac/introduce.php) · 自动 English
- [TickTick/滴答清单](https://dida365.com/#q/all/tasks) · 万能 Inbox、GTD 工具
- [有道词典](http://cidian.youdao.com/index-mac.html) · 取词/查词、生词本
- [EverNote/印象笔记](https://www.yinxiang.com/?from=evernote) · 资料备查 #78 #140 
- [Pomotodo](https://pomotodo.com/app/) · 好用的 TODO & 番茄
- [Near Lock](http://nearlock.me/) · 配合 iPhone 自动解锁、输入密码
- [Noizio](http://noiz.io/) · 白噪声（全局快捷键）
- [XMind](http://www.xmind.net/download/mac/) · 思维脑图
- [HyperDock](https://bahoom.com/hyperdock/) · 窗口预览
- [HyperSwitch](https://bahoom.com/hyperswitch) · `Option + Tab` 切换当前 Desktop 窗口
- [Letterspace](https://programmerbird.com/letterspace/) · 基于 iCloud 文件目录的 Markdown Editor
- [Reeder](http://reederapp.com/mac/) · RSS 阅读器
- [Tickeys](http://www.yingdev.com/projects/tickeys) · 模拟键盘声音
- [Folx](http://mac.eltima.com/download-manager.html) · 下载器
- [Flux](https://justgetflux.com/) · 护眼
- [Snappy](http://snappy-app.com/) · 截图悬停
- [Helium](http://heliumfloats.com/) · 视频悬停
- [Dr. Cleaner](https://itunes.apple.com/us/app/dr.-cleaner-disk-memory-system/id921458519?mt=12) · 内存管家
- [AppCleaner](https://freemacsoft.net/appcleaner/) · 清理 Apps
- [OmniDiskSweeper](https://www.omnigroup.com/more) · 磁盘空间检测
- [Toggl](https://toggl.com/) · 时间记录
- [Irvue](https://itunes.apple.com/us/app/irvue-unsplash-wallpapers/id1039633667?mt=12) · 自动切换壁纸（from [Unsplash](https://unsplash.com/)）
- [WD MyCloud](http://mycloud.com/) · 私有云

### level 2. Web Apps

- [Instapaper](https://www.instapaper.com/u) · 完美阅读体验
- [Diigo](https://www.diigo.com/user/jimmylv) · 内容评注 #99 
- [Inbox](https://inbox.google.com) · 无敌 Email 邮箱
- [Toggl](https://toggl.com/) · 时间记录 & Reports

## References

- [装了啥 · Issue #16 · sorrycc/blog](https://github.com/sorrycc/blog/issues/16)

**Comment by JimmyLv** [comment]
@Yaowenjie @linesh-simplicity

**Comment by JimmyLv** [comment]
拆分出了专门的移动端 #141 & 各大平台型软件及其插件 #143 #142 #140 #78

**Comment by Yaowenjie** [comment]
棒！ 在推荐一个不错的软件，视频压缩剪辑转码用的：[HandBrake](https://handbrake.fr/)，以及GNU/Linux免费开源的图片处理工具：[GIMP](https://www.gimp.org/)

**Comment by JimmyLv** [comment]
@Yaowenjie 没想到如此强大

![image](https://cloud.githubusercontent.com/assets/4997466/21639110/5349284a-d2a9-11e6-84dc-3811b0574489.png)

**Comment by linesh-simplicity** [comment]
* 壁纸软件：如果你不是用自己的壁纸，可以试试这个：https://github.com/JohnCoates/Aerial 。全息壁纸。。

**Comment by JimmyLv** [comment]
```
brew cask install aerial
```

**Comment by linesh-simplicity** [comment]
万一 cache 下不下来：https://www.v2ex.com/t/235597#reply7

**Comment by linesh-simplicity** [comment]
卧槽我的工具集都被你说完了……赔钱！

**Comment by kenpusney** [comment]
关于GIMP补充一点，可以支持用Scheme（Guile）写脚本扩展（逃…

**Comment by JimmyLv** [comment]
updated at: [2017-06-19 21:41](https://github.com/JimmyLv/jimmylv.github.io/issues/121#issue-194367552)

**Comment by gentlecoder** [comment]
棒👍

**Comment by ripperhe** [comment]
作者，你好，借楼推广一下

Bob 这款软件，开源免费，翻译方式支持划词翻译、截图翻译

翻译源支持有道翻译、百度翻译、谷歌翻译

https://github.com/ripperhe/Bob

**Comment by JimmyLv** [comment]
一直在用的按键显示软件：[Keystroke Pro](https://ixeau.com/keystroke-pro/)

开源可定制的 Keyviz 看起来很香：[mulaRahul/keyviz: Keyviz is a free and open-source tool to visualize your keystrokes ⌨️ and 🖱️ mouse actions in real-time.](https://github.com/mulaRahul/keyviz)

[在屏幕上显示键盘操作的小工具（Mac系统） - 知乎](https://zhuanlan.zhihu.com/p/365357669)
