### ISSUE TITLE
React 中 JSX 的问题所在，丢失了必要的抽象

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#123]
https://egghead.io/lessons/javascript-create-a-basic-component-using-vue-js?play=yes

再一次看到了 Vue #20 如此简洁、易用的 API，其优势恰恰是由于适当、合理的抽象。

纯 JavaScript （JSX）写出的代码必然会有很高的灵活性，但与此同时却又把曾经沿用很久的抽象层级给丢失了。曾经花费多久精力才把 JS、HTML、CSS 进行了逻辑、内容、样式的分离，分别对其进行抽象并且实践出了一系列的最佳解决方案，而如今却又再一次糅杂到了一起。

**Comment by linesh-simplicity** [comment]
没用过 vue。

我觉得 JSX 带来了组件化的好处。虽然是把三者又糅合到了一起，但是它们以一个「组件」的形式高内聚到一起，而「组件」是人脑管理复杂度的一个经典方法：把相似的内容打包成一个组块（chunk）。这样，数据、状态交给 redux，很好做单元测试；样式、简单的 HTML 结构可以用 Enzyme 来测。能测试就意味着能自动化验证，能知道自己做得对不对，没毛病啊。

HTML、CSS、JS 分离的时代，也是不够完整的。CSS 和部分的 JS 必须通过选择器的方式与 html 的元素产生联系。

**Comment by JimmyLv** [comment]
Vue 是以 **.vue 文件作为一个组件的载体，一样有你所说的各种好处：

![image](https://cloud.githubusercontent.com/assets/4997466/26148532/9975e02c-3b29-11e7-86fb-64066c7eed57.png)

> CSS 和部分的 JS 必须通过选择器的方式与 html 的元素产生联系

这一点也是我钟爱 `styled-components` 的原因之一，具体的原因可以看对比：

https://gist.github.com/JimmyLv/95c3c3794d02efcce6ca5b11d5578b55

**Comment by linesh-simplicity** [comment]
卧槽什么字体这么丑！

**Comment by JimmyLv** [comment]
```jsx
export default ({ title, name}) => <Header content={this.state.flag} className="sg-Header">{`Hello ${title} · ${name}!`}</Header>
```

```jsx
connect((state)=>({
  title: state.title,
  name: statet.firstName + state.lastName
}))(SGHeader)
```

```jsx
# redux stuffs
```

**Comment by linesh-simplicity** [comment]
我服！哈哈哈哈哈！

**Comment by JimmyLv** [comment]
这才是 PKM 的最高境界！

![image](https://cloud.githubusercontent.com/assets/4997466/26150844/ef3984d8-3b32-11e7-91ff-a28d731ac4ed.png)

**Comment by JimmyLv** [comment]
close https://github.com/JimmyLv/jimmylv.github.io/issues/123

Best Regards,
Jimmy.

**Comment by JimmyLv** [comment]
close #123

**Comment by JimmyLv** [comment]
close https://github.com/JimmyLv/jimmylv.github.io/issues/198

Best Regards,
Jimmy.

**Comment by JimmyLv** [comment]
close #198

**Comment by linesh-simplicity** [comment]
没用啊！好像还是没 close 掉。

**Comment by JimmyLv** [comment]
得益于 JavaScript 语言的封装能力，自作主张重新封装 (Styled) Component 并自定义命名

vs

官方既定的 HTML 抽象规范，大伙儿一起沿用自带命名规则。

> 至此，naming things 如此艰难的又一论证。

![image](https://user-images.githubusercontent.com/4997466/28257882-7e26323e-6b00-11e7-967c-fc594d0e7cd6.png)
