### ISSUE TITLE
讨论学习的有效性

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#125]
学习前：选择正确的时机
学习中：对比学习，主题阅读
学习后：总结写作，传授他人

## 学习前：选择正确的时机

现在的时间是 `2016-12-15 21:56:37` 确实累得很，不想打字了都……

刚刚洗完澡，听着歌，感觉就很有催眠的意味… （真好，TickTick 的桌面端（即 Web 端）和手机 App 只同步数据而不会同步设置。）所以，

- 桌面端：隐藏日历，反而是在 macOS 自带日历中订阅 TickTick 的清单…
- 移动端：显示日历，不用再切换到难用的 iOS 日历，移动端切换成本高…

### 解决「不想开始」的难题

> 你不用去做那些宏伟高大的事情。即便是去做那些不重要不紧急的事情比如你现在抽一分钟出来练几个字都可以，这就赚到了，就这样开始，没错！这可以破「执行无能」。via : [「可实现的成功学」：从现在开始，你明白可以不干什么了](https://daily.zhihu.com/story/2224051)

1. 静心！处理 TickTick，~~直到看到「今天」这个清单当中为空…~~ 在接收正统的 GTD 洗礼过后，更愿意看到的是「收集箱」这个清单为空，而「今天」这个清单里面只放一些”非做不可不做就会死掉“的事项，所以说哪怕真的「今天」做不了了，就必然会有一个「下一步行动」来与人交涉是否有机会延期

2. 确定性！比如看书，能看几页算几页… 并不会有多少目标，也不会有完成目标的压力，也不需要任何产出，想做多少算多少，只要做了就有成长，嗯，轻松。

### 在正确的时间做正确的事情

比如：

- 在每天一开始（精力最充沛）的时候执行 MIT
- 精力管理 > 时间管理，之所以需要健身/运动、充足的睡眠……
- 比较累当还有精力的时候，阅读（with 标注） or 整理（@滴答清单/书签 etc）
- 特别累的时候应该及时休息，躺在床上之后看看 @微信阅读 比较乏味的理论内容易于催眠
- 在等人/饭的时候，时间较短且不确定，刷朋友圈、RSS，看到有趣的还可以即时分享
- 等飞机/火车的时候，时间较长且确定，比较安静就可以看整本整本的书 @微信阅读
- 在坐 @滴滴 /地铁的时候，车上很晃不宜阅读，就可以带上耳机听听 Podcast 或者 @得到 有声书
- 待续…… 

=> 已经将手机里首屏的 Apps 根据「场景」划分了文件夹 📂 （截图见[下一个 comment](https://github.com/JimmyLv/jimmylv.github.io/issues/125#issuecomment-269628045)）

### 可能的 Idea？

- #133 [《刻意练习：如何从新手到大师》 - Douban](https://www.douban.com/search?q=刻意练习：如何从新手到大师)
- #99 使用 Instapaper + Diigo 进行有效性提取阅读
- #134 刻意练习，录制视频进行观察

### 营造学习氛围

1. 打开 macOS 和 iOS 的「勿扰模式」
2. 清理 & 区分 Desktops via [从需求出发：再谈 macOS 下的 Mission Control | 吕立青的博客](https://blog.jimmylv.info/2015-10-31-mission-control-on-mac-os-x/)
3. 开启一个番茄（with 白噪声） @潮汐，打开 @Toggl 计时，中途任何想法都记录到 @TickTick （均可使用快捷键）

### 因地制宜：不同的学习内容有不同的学习方式

- 阅读
- 看视频
- ……

更多学习方式参考：[读万卷书不如行万里路，行万里路不如互联网学习 - 吕立青的博客](https://blog.jimmylv.info/2015-02-12-internet-learning-better-than-reading-book/)

## 学习后

1. 如何快速输出一场 Session or Workshop？#135
  - 参考以往经验 #101 #119 
  - 仿照 QA Community 所输出的四类活动 checklist
  - TickTick -> 思维导图 -> Slide as MVP -> Article as Notes（直接先把文章写好，eg: #116 ） 
2. 总结套路，花费时间 etc
  - 比如说每个月即每个迭代的时间复盘 #107 
  - 上次的 #119 的简单总结 https://github.com/JimmyLv/jimmylv.github.io/issues/119#issuecomment-267657173

**Comment by JimmyLv** [comment]
学习前：选择正确的时机

现在的时间是 `2016-12-15 21:56:37` 确实累得很，不想打字了都……

刚刚洗完澡，感觉就很有催眠的意味…

事情还很多、Annual Review，JoJo 又不会回… 等同事把写 Review 的套路熟悉之后我再让他们写吧，重点在挖掘，很多事情有对比才会有示例。

真好，TickTick 的桌面端（即 Web 端）和手机 App 只同步数据而不会同步设置。

所以，

- 桌面端：隐藏日历，反而是在 macOS 自带日历中订阅 TickTick 的清单…
- 移动端：显示日历，不用再切换到难用的 iOS 日历，移动端切换成本高…

1. 静心！处理 TickTick，直到看到「今天」这个清单当中为空…

![](http://7xjbdq.com1.z0.glb.clouddn.com/images/2016/1481812071356.png)

2. 确定性！比如看书，能看几页算几页…

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/21544554/f405e0e6-ce0a-11e6-858b-5481998696d1.png)

**Comment by JimmyLv** [comment]
@linesh-simplicity @Yaowenjie 来收干货吧，😂

**Comment by Yaowenjie** [comment]
过完年了，感觉可以收起啦~ 👍 👍 👍  新年搞起来~
