### ISSUE TITLE
Chrome Extensions 专题

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#140]
## 前言

- [x] 确定分类（根据 [Chrome 网上应用店 - 扩展程序](https://chrome.google.com/webstore/category/extensions)的官方分类来获得概览）
- [x] 修改为自己的工具集分类（可以直接用 [SimpleExtManager Options](chrome-extension://kniehgiejgnnpgojkdhhjbgbllnfkfdk/options.html) 创建 group）
- [x] 先删除已经完全不用的 Extensions `chrome://extensions/`
- [x] 给每个 Extension 添加功能详情与使用方式（快捷键）

### 网站/博客相关

- ~~DomainFlag~~
- ~~SimilarTech Prospecting~~
- ~~WhatRuns~~
- Wappalyzer（查看当前网站所用到的技术，亮点在于可以直接显示 Tech 图标）

### 知识管理/阅读

- Copy As Markdown · 不一样的 Copy `Alt + C`
- Diigo Web Collector - Capture and Annotate 
    + **Save Bookmark `Ctrl +  Alt + S`**
    + **Annotate Article `Ctrl +  Alt + E`**
    + Annotate PDF `Ctrl +  Alt + P`
    + Annotate Screenshot `Ctrl +  Alt + W`
    + Annotate `Ctrl +  Alt + A`
    + Read Later `Ctrl +  Alt + R`
    + **Open outliner sidebar `Ctrl +  Alt + O`**
- Evernote Web Clipper · `~`
- Smart TOC 
    + toggle show/hide `Cmd + E`
    + Jump to next heading `Cmd + Shift + E`
    + Jump to previous heading `Cmd + Shift + R`
- ~~Instapaper · `Cmd + Shift + S`~~ -> **AcceleReader for Instapaper**
    + Coderbility（Code Hilights）
    + Instapaper count
    + Instapaper highlights exporter
- Feedly Subscribe Button（replace ~~RSS Subscription Extension (by Google)~~）
- _* Remarkerbe_
- _* WorkFlowy_
    + _WorkFindy for WorkFlowy_
    + _WorkFlowyPlus_
    + _WorkFlowy for Coders_
- _* 方片收集_
- 為什麼你們就是不能加個空格呢？· 强迫症患者 · 更好的中英混合排版效果

### 开发者工具

- 框架辅助
    + React Developer Tools · `Cmd + Alt + I`
    + Redux DevTools · `Cmd + Alt + I`
    + _* Augury（Angular）_
    + _* Vue.js devtools_
    + _* Vulcan by Firebase_
- 前端相关
    + Daydream（to record nightmare script）
    + CSSViewer （快速查看 CSS Properties）
    + ColorZilla （取色工具）
    + Emmet Re:view （多 mobile 屏幕同时显示，同步点击操作）
    + IcoMoon（to create Icons）
    + JavaScript and CSS Code Beautifier
    + JSON Viewer （查看格式化的 JSON）
    + Lighthouse （网站性能评估与优化建议）
    + ModHeader （注入想要的 HTTP Header）
    + Page Ruler （尺子）
    + Postman （调戏 APIs）
    + jQuery Inject （注入 jQuery，快速选择网页内想要的内容）
    + WrapAPI （把网页变成 API）
- GitHub 相关
    + Awesome Autocomplete for GitHub
    + Codelf-Best GitHub Stars organizer
    + GistBox Clipper
    + github code review extension
    + GitHub Hovercard
    + Github Travis Stat
    + Isometric Contributions
    + OctoLinker
    + Octotree
    + Omnibox for Github
    + Refined GitHub
    + Sourcegraph for GitHub
    + ZenHub for GitHub

### Chrome 美化与主题

- [Minimal White](https://chrome.google.com/webstore/detail/minimal-white/clcbojcafbggjenbeflknhfimpcikmlc)
- AdBlock（拦截广告x1）
- Advertising Terminator（拦截广告x2）
- DevTools Author
- Dream Afar New Tab
- Panda 5 | News & Inspiration Dashboard
- Stylish - Custom themes for any website
- _* iZhihu_
- _* 微博急简 WC_
- 豆藤 Bean vine · 网盘搜电影，电子书价格

### 效率/生产力

- ~~Pomotodo~~
- TickTick - Todo & Task List · `Cmd + Shift + L` 刚好覆盖 macOS 锁屏快捷键
- _* Pushbullet_ · 还是 Handoff 好用，macOS 和 iOS 跨设备神器
- Simple QR Generator · 如果 Handoff 不生效，就用微信扫一扫吧
- _* QuadroSync Helper_ · 与 iPhone 互动
- Google Docs Offline
- Google Drawings
- ~~Toggl Button: Productivity & Time Tracker~~
- _* WakaTime_ · 计时工具
- _* Wave_ · 多人协作工具

### 原生功能增强

- Better Bookmark（Easily add bookmarks to any category.）· `Cmd + D`
- Better History · `Cmd + Y`
- Chrono Download Manager （Better Download）· `Cmd + J`
- SimpleExtManager（Better Extension）· `Cmd + Shift + P`
- ~~SimpleUndoClose~~ -> `ox` `oh`
- ~~Popup my Bookmarks~~ -> `b` + `Tab`
- ~~EverSync - Sync bookmarks, backup favorites~~ -> Chrome 自带就好
- Exporter （百度网盘必备）+ Aria2GUI
- 云盘万能钥匙
- Folx
- HD for YouTube™
- Turn Off the Lights
- LastPass: Free Password Manager · `Cmd + I`
- Data Saver
- HTTPS Everywhere
- Clutter Free
- OneTab
- The Great Suspender
- _* Proxy SwitchyOmega_
- **Surfingkeys**（replace Vimium && Vimium++）
- Tampermonkey
- Yet Another Drag and Go FIX
    + LU: `http://en.wikipedia.org/wiki/How%s`
    + RU: `https://www.google.com/search?q=%s`
    + LD: `http://www.douban.com/search?q=%s`
    + RD: `http://www.zhihu.com/search?q=%s`

### 搜索辅助

- _AutoPagerize_（在看 GitHub Issues 时有 bug）
- Multi-highlight · `Cmd + Shift + M`
- word highlight
- Omnibox Site Search · `site {query}`
- WorldBrain - The (Re)search-Engine · `w {query}`
- Search by Image (by Google)
- Wikiwand: Wikipedia Modernized

### 辅助输入

- [Grammarly](https://app.grammarly.com/)
- Makedown（Enable Markdown editing on Zhihu.）
- Markdown Here · `Alt + M`
- Type Fu · 从提供打字速度开始（最新版已有代码版）

### 购物

- 懒人比价购物助手
- _支付宝安全插件_
- 购物党比价工具

~~### 社交与通讯~~
~~### 体育~~
~~### 无障碍~~
~~### 新闻与天气~~
~~### 娱乐~~
~~### 照片~~

**Comment by linesh-simplicity** [comment]
我觉得我现在的人眼辨别能力很好，怕用了 Grammarly 以后就要被机器取代了…试用了一下确实酸爽，哈哈哈

**Comment by JimmyLv** [comment]
Synatx highlight for all textarea.

**Comment by kenpusney** [comment]
我觉得吧，只能在英文环境下用的东西多少还是不靠谱的。

毕竟每年还是要写不少知乎答案的。（逃

**Comment by JimmyLv** [comment]
花了将近 3 小时，终于算是整理完毕收工。

**Comment by JimmyLv** [comment]
SimpleExtManager 更新为 [Extension Manager - Chrome Web Store](https://chrome.google.com/webstore/detail/extension-manager/gjldcdngmdknpinoemndlidpcabkggco)

**Comment by JimmyLv** [comment]
> 我觉得我现在的人眼辨别能力很好，怕用了 Grammarly 以后就要被机器取代了…试用了一下确实酸爽，哈哈哈

@linesh-simplicity 配合DeepL简直不要太酸爽，玩过 github copilot 才真的觉得要被取代了😂
