### ISSUE TITLE
Sublime Packages 专题

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#142]
直接备份看结果，ref [Syncing - Package Control](https://packagecontrol.io/docs/syncing)，`/Users/Jing/Library/Application Support/Sublime Text 3/Installed Packages`：

### 原生功能增强

- Package Control · SublimeText 插件进阶第一步
- AdvancedNewFile · 新建文件的好办法
- _* AutoFileName_
- Open Finder · `finder: Open here`
- _* Nettuts+ Fetch_ · 直接从 CDN 下载一些包
- SideBarEnhancements · 多了好一些功能，`rename`
- SyncedSideBar · 选择文件同步滚动

### Git & GitHub

- Git · `pull`, `push`, `commit`
- GitGutter · 显示修改行
- **GitHubIssue** · 神器！参考 #258
- Github Tools · 快速打开 GitHub 对应网页

### 编辑/写作功能

- Evernote · 把 SublimeText 变成印象笔记编辑器 
- Jekyll · 新建草稿，管理文章
- Markdown Extended · 语法
- **MarkdownEditing** · Markdown 语法便捷输入
- PlainNotes · 做笔记，管理 TODOs 很好用
- _* RawLineEdit_ · 显示行尾换行符
- TextFormatting · 格式化 JSON 之类
- _* Typewriter_ · 打字机效果？

### 开发相关 · 前端

- BracketHighlighter · 括号标识
- CTags · 修整 XML
- Color Highlighter · 显示颜色 `#fff`
- ES6-Toolkit
- Emmet · 简化 HTML 输入
- Tag
- JSX
- JsFormat · 格式化 JavaScript
- LESS
- PyV8

### Theme 与语法高亮

- Themr · 随机主题，😂
- Theme - Broceanic
- Theme - Brogrammer
- Theme - Cyanide
- Theme - Spacegray
- Theme - itg.flat
- Monokai Extended · 原生高亮扩展，支持 Markdown 之类的
- **Material Theme** · 主题配色 Material-Theme-Lighter
- **Oceanic Next Color Scheme** · 高亮配色 Wallaby/Oceanic Next (SL)
- JavaScriptNext - ES6 Syntax · 高级语法支持，否则高亮有问题

**Comment by linesh-simplicity** [comment]
快快补齐这个 issue。

我已经决定形成 Intellij(WebStorm) + Sublime + Vim 的编辑体系了。锤炼技艺中。

那天看到一个~~冷~~笑话说，我会选择用 vim 是因为不知道怎么改 `core.editor = 'vim'` 的配置。。。

**Comment by JimmyLv** [comment]
```
zshconfig
```

**Comment by linesh-simplicity** [comment]
![image](https://cloud.githubusercontent.com/assets/11895199/26149894/b40ddc0a-3b2e-11e7-999f-9d925e4ab2b5.png)

 (ಥ﹏ಥ)

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/26150746/67792274-3b32-11e7-9dd6-ec79722bca0c.png)

这不是 zsh 自带的 alais example 么，😂

**Comment by linesh-simplicity** [comment]
当然不是 😂

![image](https://cloud.githubusercontent.com/assets/11895199/26150832/e260fc3c-3b32-11e7-99d5-1bbaa40bc27f.png)

**Comment by linesh-simplicity** [comment]
![image](https://cloud.githubusercontent.com/assets/11895199/26151197/3f52c1a4-3b34-11e7-90fb-130d9ba8d877.png)

vim-iterm 😂

**Comment by linesh-simplicity** [comment]
不知道为什么 WebStorm 突然能看视频了 😂

![image](https://cloud.githubusercontent.com/assets/11895199/26151260/90571eec-3b34-11e7-9f73-7ede57f7af5a.png)

**Comment by JimmyLv** [comment]
卧槽这么厉害啊！
