### ISSUE TITLE
Intellij IDEA/WebStorm 与相关 Plugins 专题

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#143]
## IDE 布局

![](https://o7mw3gkkh.qnssl.com/images/2017/09/1506066719465.png)

- 00 运行 npm 脚本 · ⌘+0
- 01 文件夹系统（设置只显示 Project）· ⌘+1
- 02 当前文件结构（方便找函数）· ⌘+2
- 03 所有可以通过 ⌘+数字 打开的快捷窗口
- 04 Run & Debug · 先 Edit 好然后 ⌃+R & ⌃+D  · 如果在 Run 窗口就可以 ⌘+R 和 ⌘+F2 运行和停止
- 05 Event Log 通常不用关心，IDE 运行任务出错或插件有更新等等
- 06 配合 GitHub Issue 作为 TODOs 特别美好 · ⌘+⌃+T
- 07 Bookmarks 比 Favorites 更进一步直接订书签 · ⌃+⇧+num ⌥+⌃+num 还可以用 ⌘+7
- 08 直接能够获取当前依赖的最新版本号 · ⌃+Space 
 	+ 再也不用 ⌘+8 打开命令行 yarn add 或者 npm install 
- 09 Git 版本管理相关
	+ ⌘+⌥+Z revert · 选择文件名或者局部内容
	+ ⌘+T update · 更新（设置默认为 stash+rebase 而不是 merge）
	+ ⌘+K commit · 配合插件可以选择固定 template，也可以有一些 hook 操作
	+ ⌘+⇧+K push · 还可以选择是否 push Tags 和 运行 Git Hooks
	+ ⌘+9 · 查看 history 及其他操作也是很美好的，特别是 undo, reword
- 10 最近打开的文件 · ⌘+E 如果没有搜到就直接 ↩ 打开全局文件搜索
- 11 文件路径 以及每个文件下面的 面包屑
- 12 快速切换 Git 分支 等配置

## Feature As Plugins（功能即插件）

![](https://o7mw3gkkh.qnssl.com/images/2017/09/1506072116005.png)

看了 Plugin 的自定义列表才意识到 WebStorm 的强大都不需要社区各种插件的加持（其实是积极得吸引社区定制化的 Plugins 然后直接列入官方插件库，比如对 [Styled-Comopnents](https://github.com/styled-components/webstorm-styled-components) 的支持），其 IDE 本身的设计就是插件式的随时插拔，搭配组合成最强大的框架/语言辅助工具。Intellij 是 Java 世界的集大成者，而 WebStorm 或者是 PyCharm 则是特定语言的相关插件配合基础插件打造而成，只取该语言所必备的 Featues 再然后就是减轻负担提高运行效率，值得好好研究与定制。

功能太多太强大，善用 ⌘+H 和 ⌘+⇧+A 寻找相应的功能！

## References 

- [高效地使用你的 IntelliJ](https://mp.weixin.qq.com/s?__biz=MzIzMTYzOTYzNA==&mid=2247483762&idx=2&sn=1cc04214ef37b4adf48d4350ece70340&chksm=e8a05e4fdfd7d7598c268a517c840d017ef37d596ad2ea0bf6fc59c0221188235a159d3658f4#rd)
- [WebStorm Blog | Tips & tricks, news, how-to’s](https://blog.jetbrains.com/webstorm/)
- [WebStorm Videos - YouTube](https://www.youtube.com/playlist?list=PLQ176FUIyIUYnLuYVKM6JhVd6ukPgzdW7)
- [WebStorm_ReferenceCard.pdf](https://resources.jetbrains.com/storage/products/webstorm/docs/WebStorm_ReferenceCard.pdf)

**Comment by linesh-simplicity** [comment]
为什么 emoji 一次只能点一个。抱歉我只能忍受给你点两个了

**Comment by JimmyLv** [comment]
i18n robot https://i18ns.com/plugin.html

**Comment by JimmyLv** [comment]
@updated(2019-07-23 11:08:13 PM)

[limited-wip/README.md at master · dkandalov/limited-wip](https://github.com/dkandalov/limited-wip/blob/master/README.md#limited-wip)

**Comment by linesh-simplicity** [comment]
![image](https://user-images.githubusercontent.com/11895199/61768224-609f9f80-ae19-11e9-8158-c761f5f53813.png)

和你是不一样的路线~我走的是极简风~

WebStorm升了2019.2后，连上面那根bar也没有了。强迫症患者比较给好评！这样在非全屏模式下也没有了任何干扰。我只想写代码（也许还有运行测试），其他那些功能区统统不想看见~都可以藏在底下通过快捷键调出哟。

**Comment by JimmyLv** [comment]
卧槽，简直太牛逼了！！

**Comment by futantan** [comment]
> ![image](https://user-images.githubusercontent.com/11895199/61768224-609f9f80-ae19-11e9-8158-c761f5f53813.png)
> 
> 和你是不一样的路线~ 我走的是极简风~
> 
> WebStorm升了2019.2后，连上面那根bar也没有了。强迫症患者比较给好评！这样在非全屏模式下也没有了任何干扰。我只想写代码（也许还有运行测试），其他那些功能区统统不想看见~都可以藏在底下通过快捷键调出哟。

最上面的 bar 如何隐藏呀，升级到了 2019.2 没有搜索到相关的配置😂

**Comment by futantan** [comment]
找到了，是 Material Theme 的配置。但是我打开这个选项之后，内容会顶上去，有点难受。

**Comment by JimmyLv** [comment]
@futantan 我现在是把 menu bar 改成黑色了，暂时求个心理安慰，哈哈哈
