### ISSUE TITLE
英语提升计划

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#148]
重点是制定自己的**计划**！

半小时：

- @多说英语
- @生词本 

年后公司会有专门的英语培训，跟着学呗，Learning English…

试听课

- [x] 新东方
- [x] 国际私塾
- [ ] ...

**Comment by JimmyLv** [comment]
不错的，试验下来，每天的量不是很多，能坚持。

![image](https://cloud.githubusercontent.com/assets/4997466/22252687/fd1d971c-e289-11e6-805c-0af2de9771ad.png)

**Comment by linesh-simplicity** [comment]
点个赞！有什么心得记得来分享！！！~~~
