### ISSUE TITLE
建立多个 GitHub 账号以便于 Assign 不同的角色

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#158]
## Description

- What's Target？
  - create different roles for GitHub Issues
  - so that each card can be assigned differently
- What's Problem？
  - switch between different roles
- What's

## TODOs

- [ ] Elaboration of this issue

## References

- [SessionBox - Free multi login to any website - Chrome Web Store](https://chrome.google.com/webstore/detail/sessionbox-free-multi-log/megbklhjamjbcafknkgmokldgolkdfig/related?hl=en-US)

**Comment by linesh-simplicity** [comment]
卧槽！我根本没想过这个问题。

**Comment by JimmyLv** [comment]
实在没必要，组织不同的会议 #Retro #IPM #Elaboration，切换至不同角色即可。
