### ISSUE TITLE
Learning-Redux 着重数据结构设计与数据流，处理异步请求

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#16]
重点学习和研究：
- [Getting Started with Redux - Course by @dan_abramov @eggheadio](https://egghead.io/courses/getting-started-with-redux)
- [Building React Applications with Idiomatic Redux - Course by @dan_abramov @eggheadio](https://egghead.io/courses/building-react-applications-with-idiomatic-redux)
- [erikras/ducks-modular-redux: A proposal for bundling reducers, action types and actions when using Redux](https://github.com/erikras/ducks-modular-redux)
- [dvajs/dva: React and redux based, lightweight and elm-style framework. (Inspired by choo)](https://github.com/dvajs/dva)
- [【译】Redux + React 应用程序架构的 3 条规范（内附实例） | 最美博客](http://haiku.jimmylv.info/#/note-blog/翻译/2016-07-04-rules-for-structuring-redux-applications/?_k=aonero)

**Comment by JimmyLv** [comment]
redux 的缺点：

- 手动管理数据流(是好也是坏)
- 异步很恼火，redux-thunk并不好用
- 拆分了很多模块，但其实都是要用的，react-redux，react-router-redux
- redux-saga 处理异步很爽，但为啥不直接用 mobx 呢？

**Comment by JimmyLv** [comment]
特别是因为 redux 里面的概念和东西一多，文件目录的结构也跟着变多变混乱，还有专门的 duck 和实践文章来解释按 features 分类的好处，坑爹呢这是！

**Comment by JimmyLv** [comment]
[Why Redux is the Future of Angular 2.0 and React - YouTube](https://youtu.be/-EyWq5XP6T8?t=412]

![image](https://cloud.githubusercontent.com/assets/4997466/18809342/84694cb4-82ab-11e6-92e6-523d0074a20c.png)

**Comment by JimmyLv** [comment]
在最近的 Workshop 算作一种总结与实践。

[react-workshop/README.md at master · JimmyLv/react-workshop](https://github.com/JimmyLv/react-workshop/blob/master/workshops/02-redux/README.md)

[2. Redux · Issue #142 · linesh-simplicity/linesh-simplicity.github.io](https://github.com/linesh-simplicity/linesh-simplicity.github.io/issues/142)

**Comment by JimmyLv** [comment]
最佳实践在 dva：[JimmyLv/demo.create-react-app-typescript: create-react-app, typescript, styled-components, dva(redux, redux-saga), ant-design http://dva.jimmylv.info](https://github.com/JimmyLv/demo.create-react-app-typescript)

**Comment by linesh-simplicity** [comment]
比我先起步了一年啊…

**Comment by JimmyLv** [comment]
@linesh-simplicity 然而现在都还没到实际工作的项目中用过……
