### ISSUE TITLE
大公司背景（多环境多参数配置）

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#162]
## Description

- What's Target？
  - 把工程化进行到底…
  - 三靠谱的多环境
  - CI/CD 持续实践
- What's Problem？
  - 小 demo 已经不能再满足于我了
- What's

## TODOs

- [x] Elaboration of this issue

## References

-

**Comment by linesh-simplicity** [comment]
同感。我也有这个困惑，抄个 issue。

* PSS 的多环境、多 region 发布策略
* CI/CD 环境

yidong 那天说某国内项目就没有 CI/CD，代码都是 QA 手动拷到外网的某个机器上面部署……相比之下现在的 CI/CD 真的很值得学习的说。

**Comment by JimmyLv** [comment]
- `NODE_ENV`: production development
- `STAGE_ENV`: local, dev, sys  uat, sandbox, prod
- `ENABLE_MOCK`

Docker k8s 接收环境变量
Jenkins 注入环境变量

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JimmyLv** [comment]
[motdotla/dotenv: Loads environment variables from .env for nodejs projects.](https://github.com/motdotla/dotenv)

vue-cli
nuxt
create-react-app

**Comment by linesh-simplicity** [comment]
dot.env这个东西似乎只支持 `.env` 和 `.env.prod`…

**Comment by JimmyLv** [comment]
可以人为根据不同 ENV require 不同 .env 文件嘛，Vue CLI 做得挺不错：

```bash
.env                # 在所有的环境中被载入
.env.local          # 在所有的环境中被载入，但会被 git 忽略
.env.[mode]         # 只在指定的模式中被载入
.env.[mode].local   # 只在指定的模式中被载入，但会被 git 忽略
```

ref: [环境变量和模式 | Vue CLI](https://cli.vuejs.org/zh/guide/mode-and-env.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E5%92%8C%E6%A8%A1%E5%BC%8F)
