### ISSUE TITLE
利用 Diigo API 写一个 Alfred 搜索的 Workflow

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#174]

**Comment by JimmyLv** [comment]
根本不用 API 啊，基本的搜索用 URL 就好了，Alfred 的自定义搜索真是棒呆！

![image](https://cloud.githubusercontent.com/assets/4997466/25086161/617251ca-23a9-11e7-8942-7ffe71e6ed61.png)

![image](https://cloud.githubusercontent.com/assets/4997466/25086164/67e37520-23a9-11e7-8f1f-a4fe3399bdda.png)

![image](https://cloud.githubusercontent.com/assets/4997466/25086148/4a82b586-23a9-11e7-9ff9-8fed20afa7ac.png)

**Comment by linesh-simplicity** [comment]
![image](https://cloud.githubusercontent.com/assets/11895199/25086365/c27d9aac-2399-11e7-8ae1-a16465f47da2.png)

![image](https://cloud.githubusercontent.com/assets/11895199/25086367/c78b811c-2399-11e7-8b4d-9031228814f1.png)

卧槽我这白边…
