### ISSUE TITLE
Common Configuration as Git Submodule

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#185]
### ⓹ 明确「下一步行动」

- .babelrc <git@github.com:JimmyLv/_babelrc.git>
- .eslintrc
- .travis.yml

## References

- https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

**Comment by JimmyLv** [comment]
react-scripts 是一个方案

**Comment by linesh-simplicity** [comment]
话说我接触 M*M 的时候也看了这篇 git submodule 的文章，猿粪啊哈哈哈。

**Comment by JimmyLv** [comment]
啥子M*M啊 哈哈哈

**Comment by linesh-simplicity** [comment]
My ***** Manager 啊~

**Comment by JimmyLv** [comment]
哈哈哈，是的，现在回想起来觉得特脑残… 

不过确实是 migration 老项目到新项目中间阶段的一种 solution

**Comment by JimmyLv** [comment]
如果在前端的话，作为 NPM modules 发布也不错，比如说各种基于 create-react-app cli 的 [react-scripts](https://www.google.com/search?q=react+scripts#newwindow=1&q=+site:npmjs.com+react+scripts):

![image](https://cloud.githubusercontent.com/assets/4997466/26148315/cdcc63f6-3b28-11e7-8e5e-ec73f1306490.png)

最终目的有二：

1. 解耦各个项目个性化的 configuration
2. 并依然可以使用统一一套 cli commands （作为~广义的~ API 暴露出去）

**Comment by linesh-simplicity** [comment]
对啦~

**个性化的配置**和**统一的使用接口**。之前在公司的 Stash 下留了个 developer-experience 的仓库，就是考虑到后者，使用了 npm modules 作为安装方式，`npm install` 完就能用多爽啊。不过没写 `README.md`，估计仓库还是要废了~\(≧▽≦)/~

**Comment by JimmyLv** [comment]
决定在项目上尝试一把 create-react-app + 自定义 $uncorp-react-scripts + template 的做法。
