### ISSUE TITLE
翻译 The Art of Platform Thinking

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#200]
## 项目纵向拆分

[The Art of Platform Thinking | ThoughtWorks](https://www.thoughtworks.com/insights/blog/art-platform-thinking)

## References

- ![](https://www.google.com/s2/favicons?domain=www.thoughtworks.com) [The Art of Platform Thinking | ThoughtWorks](https://www.thoughtworks.com/insights/blog/art-platform-thinking)
- ![](https://www.google.com/s2/favicons?domain=www.thoughtworks.com) [ThoughtWorks | Creative technology consultants](https://www.thoughtworks.com/digital-platform-strategy)
- ![](https://www.google.com/s2/favicons?domain=www.thoughtworks.com) [数字化平台战略 | ThoughtWorks](https://www.thoughtworks.com/cn/talks/dps-tech-radar-summit-05-2017)
- ![](https://www.google.com/s2/favicons?domain=zhuanlan.zhihu.com) [数字化企业的交付基础设施 - 知乎专栏](https://zhuanlan.zhihu.com/p/26760367)
- ![](https://www.google.com/s2/favicons?domain=) [Digital PlatformV5.key](http://file///Users/Jing/Downloads/%E6%95%B0%E5%AD%97%E5%8C%96%E5%B9%B3%E5%8F%B0%E6%88%98%E7%95%A5-%E6%9B%BE%E5%AD%A6%E6%B5%B7.pdf)
- ![](https://www.google.com/s2/favicons?domain=www.itdks.com) [数字化平台战略 - IT大咖说 - 大咖干货，不再错过](http://www.itdks.com/dakashuo/detail/1382)

**Comment by linesh-simplicity** [comment]
8好意思，我给懒忘了，还需要么…

**Comment by JimmyLv** [comment]
@linesh-simplicity  sure, I am waiting for you.

**Comment by JimmyLv** [comment]
润色部分好难，花费时间远远、远远多于预期。

**Comment by linesh-simplicity** [comment]
呃，看来还没润色完！
