### ISSUE TITLE
项目技术雷达

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#22]
不如放到这里： https://stackshare.io/JimmyLv 「[截图](https://github.com/JimmyLv/jimmylv.github.io/issues/22#issuecomment-275113857)」

project | tech stack | notes
--------|-----------|-------
osp-ui | [![StackShare](https://img.shields.io/badge/tech-stack-0690fa.svg?style=flat)](https://stackshare.io/JimmyLv/osp-ui) | 前端，React Components，AEM，Atomic Design
osp-api | [![StackShare](https://img.shields.io/badge/tech-stack-57CB80.svg?style=flat)](https://stackshare.io/JimmyLv/osp-api) | 后端，MicroService，AWS，SSO，Spring-XX

示例（但是表格的形式还是太难编辑和查看）： 

Tech Stack | Icon | Function | Category | Description | Notes | References
-----------|------|----------|----------|-------------|-------|------------
[Enzyme](https://stackshare.io/enzyme) | [![Enzyme](https://img.stackshare.io/service/4488/enzyme.png)](https://stackshare.io/enzyme) | [Javascript Testing Framework](https://stackshare.io/javascript-testing-framework) | [Build, Test, Deploy](https://stackshare.io/build-test-deploy) | React 组件测试必备，提供了浅渲染解决方案与优雅的 API | mocha、mocha-webpack、mocha-junit-reporter、enzyme、chai、chai-enzyme、sinon、sinon-stub-promise、jsdom | [「技术雷达」之使用 Enzyme 测试 React（Native）组件 | 吕立青的博客](https://blog.jimmylv.info/2016-12-07-react-testing-with-enzyme/)

或者这里：

- [Siftery | Share products you use at work, explore what others are using](https://siftery.com/#) => 不能自己添加新的工具，也不能集结成集
- [Awesomes - Web前端开发资源库](https://www.awesomes.cn/mem) => 功能还不错，但是不能添加每个技术栈的使用详情
- [SDK.CN - 中国领先的开发者服务平台](https://www.sdk.cn/company/create) => 页面太丑

## TODOs

1. save file with `22.md` name on sublime text so that you can open it quickly by using `Ctrl+P` 

一时间没找到总结项目的手段，然后发现从 TechRadar 入门是一个不错的选择，其实总结项目，总结的并不是项目本身，而是自己的技术栈，只是因为项目离自己最近而已。

## Ideas

> 雷达应该是侦测你的期望，而不是责怪过去。

那么该用何种形式来回顾自己或项目上的技术栈？

于个人而言，可以把四个阶段划分为：

- 不学（暂缓，这东西可能要被淘汰了，投资回报没有价值）
- 观望（评估，这东西可能要火，但是现在下手性价比不高，还有更重要的事情要做）
- 学习（试验，这东西在项目上都已经用上了，自己也开始实践并且总结一些经验）
- 深入（采用，这玩意儿用过之后真不错，想去看看源码是怎么玩儿的，值得深入背后的理念和思想）

## References

- [x] 自制技术雷达 ref: [打造你自己的技术雷达 – ThoughtWorks洞见](http://insights.thoughtworkers.org/build-your-own-technology-radar/)
- [x] 工具已找到：
  - [bdargan/techradar: Build your own Technology Radar. Inspired by ThoughtWorks Technology Radar.](https://github.com/bdargan/techradar)
  - [zalando/tech-radar: A tool to help teams make the right technology choices](https://github.com/zalando/tech-radar)
  - [tnunamak/tech-radar: An interactive technology radar inspired by ThoughtWorks](https://github.com/tnunamak/tech-radar) 
  - 或者自己仿照撸一个：WYSIWYG TechRadar Editor #160

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/22293066/2720aa12-e349-11e6-81c2-3a28eb23bdd4.png)

**Comment by linesh-simplicity** [comment]
感觉又可以来收干货了。

**Comment by JimmyLv** [comment]
真心干货，切换到 Details Tab 查看具体 Description （better to `li: margin-bottom: 5px;`）：

- [OSP-UI - JimmyLv | StackShare](https://stackshare.io/JimmyLv/osp-ui)
- [OSP-API - JimmyLv | StackShare](https://stackshare.io/JimmyLv/osp-api)

这里重点总结了前端即 OSP-UI 的内容，后端 API 部分会放到 #105 总结微服务相关实践

![image](https://cloud.githubusercontent.com/assets/4997466/22325356/8d2616c2-e3e8-11e6-9872-04a661de33dd.png)

**Comment by JimmyLv** [comment]
Tech Stack | Icon | Function | Category | Description | Notes
-----------|------|----------|----------|-------------|--------
[Enzyme](https://stackshare.io/enzyme) | [![Enzyme](https://img.stackshare.io/service/4488/enzyme.png)](https://stackshare.io/enzyme) | [Javascript Testing Framework](https://stackshare.io/javascript-testing-framework) | [Build, Test, Deploy](https://stackshare.io/build-test-deploy) | React 组件测试必备，提供了浅渲染解决方案与优雅的 API | mocha mocha-webpack mocha-junit-reporter enzyme chai chai-enzyme sinon sinon-stub-promise jsdom
[Ansible](https://stackshare.io/ansible) | [![Elojna20](https://img.stackshare.io/service/663/ElOjna20.png)](https://stackshare.io/ansible) | [Server Configuration and Automation](https://stackshare.io/server-configuration-and-automation) | [Build, Test, Deploy](https://stackshare.io/build-test-deploy) | ansible scripts in common deployment repo <br> playbooks with different roles <br> different env config properties in YAML file | create (ec2) instance
[PostCSS](https://stackshare.io/postcss) | [![Rlfcjedi](https://img.stackshare.io/service/3339/rlFcjEdI.png)](https://stackshare.io/postcss) | [CSS Pre-processors / Extensions](https://stackshare.io/css-pre-processors-extensions) | [Languages & Frameworks](https://stackshare.io/languages-and-frameworks) | autoprefixer to support multiple browsers automatically (with webpack plugin) | 
[Selenium](https://stackshare.io/selenium) | [![Big logo](https://img.stackshare.io/service/1517/big-logo.png)](https://stackshare.io/selenium) | [Browser Testing](https://stackshare.io/browser-testing) | [Build, Test, Deploy](https://stackshare.io/build-test-deploy) | E2E testing | *nightwatch *robot framework
