### ISSUE TITLE
Web 开发相关技术总结

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#23]
### 计划演变

1. 更改 Title 的原因在于，我的目的只是为了**整理知识结构**，参考演讲[一个前端的自我修养](http://taobaofed.org/blog/2016/03/23/the-growth-of-front-end/)所提到的知识的全面性。
2. 而思维导图只是组织内容的其中一种「简化」形式，对比 XMind、Workflowy、OneNote 等工具，就会发现 OneNote 可以兼顾知识结构性、内容多样性以及功能操作的丰富性。
3. [OneNote 和 Evernote 应如何取舍？ - 知乎](https://www.zhihu.com/question/24600253)，其实不用取舍，各取所长即可，感谢这个世界上的竞争者们，竞相创造着更加美好的产品。
4. #31 结合职业发展的技术需求，尽快整理出符合自身的知识体系，牢固而有力，才能够稳步向前。

### 内容规划

- 相关库 （对比：[Front-end Hyperpolyglot](https://jeffcarp.github.io/frontend-hyperpolyglot/)）
- 框架 or 库 | Framework or Library

参考 [轻量级Web应用开发 (豆瓣)](https://book.douban.com/subject/26585461/) 的讲解顺序，该书依赖于 Ruby，我在整理的时候则会同时注重 JavaScript(Node.js 服务器端)、Java、Python 语言的相关体系。

### 最佳实践

~~这几乎是梦寐以求的样子，使用 OneNote 采用可详细、可结构化的知识体系组织方式。 via [我应该用onenote还是印象笔记？ - 刘果的回答 - 知乎](https://www.zhihu.com/question/28948834/answer/42668461)~~

- 30% 碎片化整理 => Diigo 才是梦寐以求的样子，#99
- 70% 整体性学习 => 直接学习知识体系？ #44 

### References

- [dypsilon/frontend-dev-bookmarks: Manually curated collection of resources for frontend web developers.](https://github.com/dypsilon/frontend-dev-bookmarks)

**Comment by JimmyLv** [comment]
优先做这件事情可以更快得交付特别多的 points

**Comment by JimmyLv** [comment]
项目经验总结在这里：#106

**Comment by JimmyLv** [comment]
这真的是一件长路漫漫的事情，而且技术栈也会随着时间而变换，新兴的东西不断增加，也有不再使用的淘汰技术，或是因为应用场景的不同会有不同的选择。

总之重点在于「变化」，如何使用某种形式达到动态描述技术栈变化的目的呢？

或者又是技术雷达要做的事情吧、

**Comment by JimmyLv** [comment]
甚至会觉得总结并没有必要，当时间流逝，很多问题都可能不再是问题。

比如最近浏览器都开始支持 import modules 了，再来支持支持 HTTP2，会不会很美好？

**Comment by linesh-simplicity** [comment]
这个思考特别赞，下了班再来聊聊。

**Comment by JimmyLv** [comment]
性能优化部分：

- http://bubkoo.com/2015/11/19/prefetching-preloading-prebrowsing/

**Comment by JimmyLv** [comment]
项目上的简单总结，Team Sharing in $uncorp: [Components Architecture (based on React).md](https://gist.github.com/JimmyLv/a1293128146fe5a0505d7a2e09b9f8d7)
