### ISSUE TITLE
FP 进阶：HOC with Recompose

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#249]
## 项目纵向拆分

- https://egghead.io/courses/higher-order-components-with-functional-patterns-using-recompose
- https://github.com/acdlite/recompose

### ⓹ 明确「下一步行动」

- [x] Write a Higher Order Component from Scratch 3:15
- [x] Compose Multiple Higher Order Components Together using Recompose 3:46
- [x] Add Local State to a Functional Stateless Component using Recompose 6:21
- [x] Add Local State with Redux-like Reducers using Recompose 2:36
- [x] Add Lifecycle Hooks to a Functional Stateless Component using Recompose 2:56
- [x] Transform Props by using the Recompose mapProps Higher Order Component 2:49
- [x] Lock Props by using the Recompose withProps Higher Order Component 2:32
- [x] Flatten a Prop using Recompose 1:10
- [x] Show a Spinner While a Component is Loading using Recompose 2:48
- [x] Show Error Messages based on Non-Optimal States with Recompose 4:34
- [x] Render Components Based on Predicates in Recompose 1:43
- [x] Set the HTML Tag of a Component via a Prop using Recompose 2:33
- [x] Optimize Expensive Computations in Recompose 1:33
- [x] Optimize Component Rendering using Recompose 6:14
- [x] Learn How Recompose Optimizes Higher Order Components 3:36

**Comment by linesh-simplicity** [comment]
少年你这是把 Github issues 作为 single source of truth 啊

**Comment by JimmyLv** [comment]
强烈推荐这个系列课程，安利 Recompose！！！

FP 编程简直太棒，组合式的思想非常易于扩展和复用，非常具备灵活性，结合 React Functional Stateless Components 简直完美。

得益于一个个 helper 函数的可自由组合性质，可以慢慢将现有项目重构到 Recompose，其中心思想依然是「消除重复」，Recompose 提供了构建于重复之上的一种高阶抽象而已，所以也可以从现有代码中先发现「代码重复」的坏味道，然后用 Recompose 将其消除即可。
