### ISSUE TITLE
给自己写 CHANGELOG

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#293]
## 项目纵向拆分

tool：https://github.com/ByronHsu/life-commit

由于重回纯文本 #288，新的一年我决定给自己写 CHANGELOG，基于当前的 MVP版本持续迭代，敏捷学习精益升级，伴随版本号哈哈哈哈，😂

- [x] 来尝试新的 PalinTask 语法作为 GitHub Issue 的打开形式 @done (18-04-13 14:55)
- [x] 测试2 
- [-] 测试3 @cancelled (18-04-13 14:54)

把自己的 TODOs 也拆分成不同层级，通过语义化体现出来：

```
feat($iWatch) - Added new productivity tool, iWatch
fix($iWatch) - Removed usless App from iWatch
feat($Blog) - Finished new article, <rethink about GTD tool>
fix($Tool) - >>>>>>>
```

然后把个人计划拆分成几个大 Feature，作为大版本升级。只允许 TrunkBasedDevelopment，简化一切。

1.0 - Consultant/Trainer
2.0 - 五本金融书籍
3.0 - 五本管理书籍
4.0 - 研究股票理财

以上例子纯属举例，新年目标完全还没想清楚。

**Comment by raywill** [comment]
up

**Comment by linesh-simplicity** [comment]
up plus

**Comment by JimmyLv** [comment]
up 主并没有更新……

**Comment by JimmyLv** [comment]
life-commit 真的很美好呀，哈哈哈 https://jimmylv.github.io/CHANGLOG.md/

统一 monorepo 在：https://github.com/JimmyLv/CHANGLOG.md

```js
packages/
  radar/
  life/
  website/
  workflow/
```

发布在 https://github.com/JimmyLv/CHANGLOG.md/releases
