### ISSUE TITLE
Rethink O$P, To be improved 技术篇 & 个人篇

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#310]
> 挖了很多坑，总会有(ﾉ*･ω･)ﾉ推倒重写的冲动。
> 
> 初衷就是帮助大家继续填坑，做 Tech Improvement 提高 Technology Skill 和 Impact。🐒

**高能预警，言论或许偏激，但旨在提供另一个思考角度。**

（免责声明：其实都不是我说的，😂）

（布道师的角度，知识源的[思维密度](https://www.zhihu.com/question/29990541)衰减。 #281）

## 项目技术篇

理解项目愿景
- 层层传递，初衷发生变化/调整（ash, la, kxxa, kxxa）
    + “敏捷”组织，**透明**|节奏|反馈
    + “客户带着我们做敏捷” “新兵训练场”
    + $uncorp 的成功之处
- TDL 文档
    + Purpose-Vision-Priorities-Business Model
    + Mobile
    + MarketPlace

具体技术栈更新，关注新特性
- 前端轮子变化快，机会也多（CSS 方案）
- 订阅更新 GitHub tools <https://github.com/JimmyLv/Haiku/pull/38>
    + [ ] renovate
- 业务相关的 tech stack
    + Redux -> rematch/dva
    + ensighten stuff
    + ……

加快**反馈**速度

> 咨询师们常常要吹所谓“敏捷”，那敏捷如何落地？如何通过技术体现出来呢？
> 不是说搞个 kanban，每天站会就是敏捷了。甚至，“敏捷是一块遮羞布”。

> （重复/手工作坊/小而美的模式，没有互联网思维，赶得上热点但落地的时候又只能热点+敏捷？）
> 开源项目 + 咨询（独占经验[间谍]；定制化调整[军师]）

- 构建、（[重构已死](https://www.zhihu.com/question/19552812/answer/79635260)）
    + "能够在单台个人电脑上复制整个生产环境，这个能力开启了整个敏捷软件开发的想象空间。测试驱动开发成为可能，持续集成成为可能，用户代表跟开发团队的紧密沟通才有必要，每天的站会、每周的迭代展示和计划会议在这个反馈周期的节奏下才有意义，注重对话的故事卡在这个节奏下才显得重要。"
    + Webpack (profiler)
        + [ ] upgrade -> v4 
        + [ ] apply `happypack`
        + [ ] enable `dll` plugin
    + (build as one part of framework: `create-react-app`, `umi.js`, `next.js`)
    + [ ] simplify build process (once for all brands, all envs: `yarn build --brand=aami --dev=sys`)
    + [ ] *Typed system (flow.js TypeScript)
    + ……
- 测试、（3X；考虑时间维度，用发展的眼光看问题；长颈鹿 | 罗马斗兽场；）
    + “3X模型”与测试三明治（“测试金字塔已死。”）
    + [ ] 增加 Unit Test
        * 什么是有价值的测试？（if-else，复杂度） #213
        * “作弊”：CDD + Snapshot Testing 
    + [ ] remove `App` component 测试 for brands (Rxi)
    + [ ] 替换 `jest` -> `mocha` (faster) #271
    + [ ] upgrade to enzyme v3 (support lifecycle method)
    + TDD 提高效率，加快**反馈**速度
    + ……
- checkstyle （团队规范的灵活性；ESLint，Git Hook；考虑成本 & 与工具的集成⬆️）
    + [ ] remove git hook
    + [ ] algin eslint rule & code style (format)
    + [ ] auto fix code in webstorm
    + [ ] code review & existing code as template （“破窗理论”）
    + ……

系统思考，前后端/架构/测试（先行？）
- BFF（“如果期望向后端发展，就去 Customer Team”）
- pact(-node) “契约一方面决定了系统架构，这个层次的设计变化不会太大；另一方面，契约本身就是 Mock 数据，可以让合作者独立并行开发。”
    + [ ] `json-server` -> `pact-node`
    + ……
- DDD（主要解决系统无法随业务演变而演变的问题。核心 Domain 不变）
    - RESTful API & SpringBoot & RxJava （技术复杂度）
    - GraphQL vs REST
    - CQRS、DDD、Redux、Rx、FRP、RP、FP

CI/CD 到底是什么？（[持续集成将死](http://gigix.thoughtworkers.org/2017/5/24/ci-dying/)）
- “越痛苦的事情越要早做。” -- tongda
- CI !== Jenkins （local 环境一致性）
    + [ ] extract Jenkins package
    + [ ] one pipeline with multiple flow
- automation testing（$uncorp 下）
- 分支策略 & Release频率
- ……

## 个人篇

复习一遍：

- 重构已死？
- 测试金字塔已死？
- 持续集成将死？

> Why?（布道师的角度，知识源的思维密度衰减。 #281）

> （重复/手工作坊/小而美的模式，没有互联网思维，赶得上热点但落地的时候又只能热点+敏捷？）
> 开源项目 + 咨询（独占经验[间谍]；定制化调整[军师]）

Windows DA 下的效率？（结合具体语境，context）

TDD 对于缓慢的 DA 意义非凡（反馈）
- 减少浪费
- “感觉”更快

新人从写测试开始，从接口开始思考软件，学习项目代码规范。

为什么需要提高效率？
- 这样才能节省时间做技术卡
- 这样才能有时间学习
- 这样才会思考和沉淀

一些软件的使用习惯

Basic：
- Todo List 的习惯：PlainTask
- 文件/笔记管理的习惯（FLT）
- OutLook 全家桶的使用

Advanced：
- Intellij/WebStorm
    + live template
    + component generater
- Chrome 的使用技巧
    + debug
    + workspace
- 命令行 alias（消除重复）
    + ssh

如何推新技术，improvements here
- 如何写邮件
- 搞定key people(魅力说服😂)
- 后续如何推进

如何快速定位问题？
- 经验 & 二分法
- SSH instance
- logfile
- debug
- splunk

个人/组织知识沉淀
- markdown 纯文本
- text -> 邮件
- confluence

目标管理OKRs，WOOP

**Comment by linesh-simplicity** [comment]
虽然说重构已死，持续集成已死。但是我觉得看看现在这个项目现状，敏捷可能只是达到一个变成政治正确的地步，很多团队离基本的敏捷都还远着，持续集成死不死的跟大多数人有什么关系呢。

话说测试金字塔怎么也死啦？

**Comment by JimmyLv** [comment]
✅ 政治正确。

这样也好，如政治一般从上至下推行也不失为一种推广方案，但愿能够真正被「下」所理解，而不是沦为「上」的新型压榨手段。
