### ISSUE TITLE
写过一段时间 Vue 之后，发现蛋疼的 React setState……

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#312]
## 项目纵向拆分

> 我写了一段时间Vue之后，   开始有点儿烦 React 了，特别讨厌 this.setState()，什么都要setState 还异步操作
反正比较烦  React setState 之后，也是有解决办法的，就是上 Redux，但是Redux实在太多模板代码了，又是个神烦。
![Pasted Image 1.png](https://shipusercontent.com/6a9a52ec6fe7f48c41cced5fa7786f9d/Pasted%20Image%201.png)
![Pasted Image 3.tiff](https://shipusercontent.com/056720b3bb9636677f1039cbbb6d6335/Pasted%20Image%203.tiff)
看看人家 vue，直接 就 this.products = xxx, 或者 this.products[index].amount = xxx
直接操作数据，还reactive，一个数据变了，其他computed的地方自动变，总之就是挺爽的。
这个组件的数据突然变了，我咋知道是谁弄的呢，怎么限制访问范围呢？
> 组件内部数据变化，就那么几种情况。
1. 组件拆得小，其实没那么多互相影响的情况。
2. 跨组件交流还是要靠 emit 事件的
3. 再不济，Vue里面有vuex，也是比Redux好用。

![Pasted Image 4.png](https://shipusercontent.com/be4a091677dddc3f55e4591cc24d16ae/Pasted%20Image%204.png)
![Pasted Image 5.png](https://shipusercontent.com/c4b13da1737a27c4ed3f9396249c75e7/Pasted%20Image%205.png)
> 是不是比Redux好懂一些，mutation嘛，肯定直接改state的。
MobX 可能就像React世界里面的Vue了，reactive 直接改数据。
如果继续用Redux，我觉得 rematch很不错。
https://rematch.gitbooks.io/rematch/content/#getting-started
[重新思考Redux - Rematch实践指南](https://rematch.gitbook.io/handbook)

### ⓵ 定义目标和原则

终极目的

Q：为什么你要花时间来做这项任务，而不是其他随便什么任务？
A：

### ⓶ 展望结果（OKRs）

利益相关人清单

Q：当你交付最终结果的时候，会如何让世界变得更好？
A：

### ⓹ 明确「下一步行动」

能够产生反馈结果的小任务

**Comment by JimmyLv** [comment]
![image](https://user-images.githubusercontent.com/4997466/41474662-26477a82-70ef-11e8-8fe1-dfc97c59ea69.png)

> Any reasons why you'd want to use Vue with JSX instead of React / Preact ?

> @_baxuz, I go for reactivity and ecosystem, vue + vue-router + vuex is designed by the same team and works perfectly with each other, it will never happen that one updates and breaks the stack, and API is designed similar ;)


examples: 

- [Vue JSX with Class example - CodeSandbox](https://codesandbox.io/s/ryp9m4jzpn)
- [Vue JSX with Class and stateless components example - CodeSandbox](https://codesandbox.io/s/ry65okmn5o)

**Comment by linesh-simplicity** [comment]
[Does anyone actually *like* React these days? ](https://twitter.com/dan_abramov/status/1006685205011234816)

**Comment by JimmyLv** [comment]
用 jsx 写 vue 或者是 MobX + React 可能就是最终答案吧，🤣
