### ISSUE TITLE
落地实践技巧：如何循序渐进提升项目单元测试覆盖率？

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#343]
🐣:添加一个单元测试覆盖率提升的hook
🐣:即每次push都会检查并更新测试覆盖率的阈值
🐣:每次提交都不能少于上一次提交，这样我们就可以持续进步，持续改进测试覆盖率啦
🐣:每次进步一点点

![](https://woundero.files.wordpress.com/2013/02/e6af8fe5a4a9e983bde6af94e5898de4b880e5a4a9e980b2e6ada5e4b880e9bb9ee9bb9e.jpg)

参考 [Koleok/jest-coverage-ratchet: Uses jest coverage output to raise acceptable coverage threshold to current coverage](https://github.com/Koleok/jest-coverage-ratchet)

配置 jest 的coverageReporters
```js
# jest.config.js
  coverageReporters: [
    "json-summary", "json", "lcov", "text", "clover"
  ],
  coverageThreshold: require('./package.json').jest.coverageThreshold
```

配置 Git hook，加到 `prepush` 里面自动更新 测试覆盖率阈值
```json
    "coverage": "lerna run coverage && git add **/package.json && git diff-index --quiet HEAD || git commit -m \"test(unit): update coverage threshold CASABASEA-1246\" --no-verify",
    ...
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "post-commit": "git update-index --again",
      "pre-commit": "lint-staged",
      "pre-push": "yarn lint && yarn test && yarn coverage"
    }
```

![](https://raw.githubusercontent.com/JimmyLv/images/master/2019/20190219135917.png)

**Comment by linesh-simplicity** [comment]
![image](https://user-images.githubusercontent.com/11895199/53000114-8daee700-3462-11e9-963b-af5bea890067.png)

**Comment by futantan** [comment]
@JimmyLv 很棒的思路👍
贴的代码里面没有自动增加覆盖率的脚本吧？

**Comment by JimmyLv** [comment]
@futantan 参考 [Koleok/jest-coverage-ratchet: Uses jest coverage output to raise acceptable coverage threshold to current coverage](https://github.com/Koleok/jest-coverage-ratchet)
