### ISSUE TITLE
基于 GitHub 的敏捷学习方法总结

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#36]
### 对时间的敬畏

你需要一个 Project Owner: Time，you need a purpose: Targets 即 Clients

then split into small projects, on different workflow but in the meantime...

在「记录时间这件小事儿 #85」里面我提到的 GTD 流程可以用于处理事件，即收集、整理、执行、回顾，而敏捷当中的几大会议显然也可以由个人完成，自己就是自己的 IM & PM，当然也是 BA & Dev & QA。

那么，迭代的概念如何进行？还是说只需要 Milestone 以实现 Iteration 即可？那就木有 Release 的压力了呢？

### Requirements

- 收集：anywhere anytime
- 整理：as BA 即分析，Elaboration & Estimation => MVP & Efforts
- 执行：as Dev&QA，Developing & Review & Testing
- 回顾：Retrospection

其他辅助

- 看板：as Jira/Trello，可视化当前进度 => GitHub Issues group by @Projects || 日历 in @滴答清单
- 晨间日记/每日回顾：as Stand-Up，只用关注 Done/Todo/Blocker & 心情 => @格志日记

### Schedule with **‘Time’**

![image](https://cloud.githubusercontent.com/assets/4997466/20562662/b6ccb2e8-b1bf-11e6-9702-755d137ab570.png)

**Comment by JimmyLv** [comment]
rename 仓库为 <jimmylv.github.io> 

「在这个互联网时代，能限制住学习的只有你的求知欲。」

互联网的精神都是开放，理应开放式学习，基于 GitHub。

**Comment by JimmyLv** [comment]
所有想法都放 GitHub Issues，每学习一样新东西都可以放同一个 [Projects · JimmyLv/jimmylv.github.io](https://github.com/JimmyLv/jimmylv.github.io/projects)

**Comment by JimmyLv** [comment]
短期的学习计划可以设立一个里程碑即 [Milestones - JimmyLv/jimmylv.github.io](https://github.com/JimmyLv/jimmylv.github.io/milestones)，设置截止日期，到期 Release，那种感觉一定很棒！

**Comment by JimmyLv** [comment]
目前来说，如果是需要分析的 Task 我就放 GitHub issues，其他时候杂七杂八的都放 TickTick（移动端 + 微信特别方便），等到要执行的时候就转移到 Pomotodo，后者用于专注，不轻易放入 task。

**Comment by JimmyLv** [comment]
GitHub 还有比较完美的数据可视化：

![image](https://cloud.githubusercontent.com/assets/4997466/18666182/0d185408-7f5d-11e6-881e-b32c0a0302ea.png)

**Comment by linesh-simplicity** [comment]
开门，来收（cha）干（shui）货（biao)了。

**Comment by Yaowenjie** [comment]
又到了。。。秋收的季节 👻

**Comment by JimmyLv** [comment]
文章已经发表至#博客大赛# https://my.thoughtworks.com

[基于 GitHub 的敏捷学习方法之道与术 - 吕立青的博客](http://blog.jimmylv.info/2016-12-04-agile-learning-based-on-github-issues/)

**Comment by JimmyLv** [comment]
目前获得的最高评价：

![image](https://cloud.githubusercontent.com/assets/4997466/21186664/58dda81c-c250-11e6-8a70-978d26797b36.png)

**Comment by Yaowenjie** [comment]
@JimmyLv 👍 男神都这么评价了~

**Comment by xiang578** [comment]
请问一下，目前你如何在电脑上处理issue，对应没有网络的环境？

**Comment by linesh-simplicity** [comment]
@Yaowenjie 你的男神竟然不是我💯差评
@JimmyLv 点赞点赞！简直厉害！效率界大神啊~

**Comment by JimmyLv** [comment]
@xiang578 我是通过 Sublime 的一个插件管理的，当然 GUI 客户端也有在用：

- Sublime：[divinites/gissues: A sublime text plug-in to manage GitHub repo issues](https://github.com/divinites/gissues)
- GUI：[Ship 2.0](https://www.realartists.com/blog/ship-20.html)

当然也在用 Sublime 管理一切，ref: https://github.com/JimmyLv/jimmylv.github.io/issues/288

任务管理：https://github.com/aziz/PlainTasks
笔记管理：https://github.com/aziz/PlainNotes
TODO管理：https://github.com/jonathandelgado/SublimeTodoReview
查询语句：https://github.com/bevesce/SublimeTodoflow
印象笔记：https://github.com/bordaigorl/sublime-evernote
GitHub Issues：https://github.com/divinites/gissues

**Comment by doitbull** [comment]
#!这样可以直接创建新issue?

**Comment by Gzxl** [comment]
#!这样可以直接创建新issue?

> #!这样可以直接创建新issue?

同请教

**Comment by JimmyLv** [comment]
#!就是这样哈
![image](https://user-images.githubusercontent.com/4997466/47406330-4c464d80-d788-11e8-984a-8acb9fef2842.png)

**Comment by JimmyLv** [comment]
难道是ZenHub？或者是只有自己的仓库才可以这样做？

**Comment by baixiaoji** [comment]
> 难道是ZenHub？或者是只有自己的仓库才可以这样做？

![image](https://user-images.githubusercontent.com/21168366/47952918-310de600-dfb1-11e8-9f81-691249346bd4.png)
其实楼主的 comment面板和我们好像不太一样，我安装了zenhub也试试了一下没有。
![image](https://user-images.githubusercontent.com/21168366/47952928-54d12c00-dfb1-11e8-983b-8dc984c53585.png)

**Comment by JimmyLv** [comment]
那个框框里面有 Create new issue的提示呀，你在框框里面输入试试呢？

**Comment by baixiaoji** [comment]
我试试了一下，发现点击到输入的框框，这个面板就消失了，原本我认为是不是我的插件影响了，后然我关闭了所有的chrome插件，也是同样的结果，去google了相关文本，结果都是回到你写的文章里提到了这点，所以还是捉急的，看到了一个方法却不能顺利实践，还在探索中
