### ISSUE TITLE
如何整理软件 Apps、模板 Templates、工作流 Workflow、片段 Snippets、配置 Configuration？

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#41]
## 个人配置/模板即资产
- [ ] 各种 `.dot` 文件即配置文件
- [ ] Intellij 设置 & Live Template
- [ ] Dash 备份
- [ ] http://ricostacruz.com/cheatsheets/
- [ ] 电脑 TimeMachine 备份
- [ ] 常用软件安装 `brew` 统一管理，摆脱难用的AppStore

**Comment by JimmyLv** [comment]
https://www.youtube.com/watch?v=bFcaO1pXzws&feature=youtu.be

**Comment by JimmyLv** [comment]
找到两个更好的 live template 

[React snippets :: JetBrains Plugin Repository](https://plugins.jetbrains.com/plugin/10113-react-snippets)
[blakedietz/js-live-template: An extensive set of javascript live templates for use with JetBrains IDEs.](https://github.com/blakedietz/js-live-template)

**Comment by linesh-simplicity** [comment]
试用了一下，React Snippets 那个跟之前用的 ReactJS Snippets 相比差不太多。

团队资产的话，感觉似乎还是需要用同一款 IDE 比较好。

**Comment by JimmyLv** [comment]
突然想到 Snippets as code，就该存在 codebase 里面，之前遇到过类似的工具：

**Comment by JimmyLv** [comment]
人生 CHANGELOG，兼 Life Radar： https://github.com/JimmyLv/CHANGLOG.md

https://github.com/JimmyLv/CHANGLOG.md/blob/master/packages/workflow/CHANGELOG.md

![image](https://user-images.githubusercontent.com/4997466/58244470-3718b800-7d85-11e9-8155-eb9596512290.png)

**Comment by JimmyLv** [comment]
目的是为了更方便迁移电脑，或是分享给他人：参考[macOS 自动化工具配置备份指南](https://sspai.com/post/57385)
