### ISSUE TITLE
Meteor 英文文档评注计划

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#5]
![image](https://cloud.githubusercontent.com/assets/4997466/14324308/cf7c31c0-fc56-11e5-917b-60b4bf7ace6e.png)

### 围绕 GitHub 学习进阶

一般的 English 文档都支持 GitBook，哪怕不支持我就手动生成一下 GitBook，所以我就可以 Download 下来 Push 到自己的 GitBook，然后在 GitBook 上进行评注，产生的评注会自动生成 Issue（或可以实现同步至GitHub？）。

**学习目的**：记录下自己的问题，并且持续跟进，搞懂过后就可以归档，即 Close 掉了。

### 工具集

- [x] GitBook 一系列插件，[Best gitbook modules for Node.js - Pincer.io](http://www.pincer.io/node/keywords/gitbook/best)
- [ ] 完美生成 SUMMARY，待试 https://www.npmjs.com/package/gitbook-summary
- [ ] ....

**Comment by linesh-simplicity** [comment]
啥，评注可以自动生成issue？

**Comment by JimmyLv** [comment]
@linesh-simplicity 不是会生成 GitBook 的 Issue 么？

**Comment by JimmyLv** [comment]
比如 Meteor 的文档就有人已经做了 GitBook 的版本，https://github.com/meteor/guide/issues/166

**Comment by JimmyLv** [comment]
### **然而！**

使用 GitBook 的缺点：

- GitBook 的评注无法同步到 GitHub，我已经提了 [Feature request: sync GitBook discussions to GitHub issues · Issue #1456 · GitbookIO/gitbook](https://github.com/GitbookIO/gitbook/issues/1456) => https://github.com/GitbookIO/feedback/issues/114
- GitBook 默认支持的评注只能编辑一行，虽然支持 Markdown 但是只有一行写毛线啊，用的 `text` 而不是 `textarea` 标签。
- 重点来了！已经写了的评注竟然不能修改，跟 GitHub 简直差太远了噶！那怎么记录我的想法并且持续更新？

所以，还是改用 Diigo 来评注英文文档吧，参见 #28
