### ISSUE TITLE
JSConf 分享

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#65]
- [NingJS - JSConf China 2016](http://2016.jsconf.cn/)
- [参加 宁JS（JSConf CN 2016）是个什么样的体验？ - 知乎](https://www.zhihu.com/question/50244455)

**Comment by JimmyLv** [comment]
无疾而终，但也明白了道理。

**Comment by JimmyLv** [comment]
[JSConf 2016: What’s better Developer Experience & How to build FullStack Application by feature? | 吕立青的博客](https://blog.jimmylv.info/2016-09-18-jsconf-summary-feature-team-and-developer-experience/)

**Comment by linesh-simplicity** [comment]
iframe 似乎挂了。对内容很感兴趣~

**Comment by linesh-simplicity** [comment]
iframe 似乎挂了。对内容很感兴趣~

**Comment by JimmyLv** [comment]
@linesh-simplicity http://jekyll.jimmylv.info/slides/2016-09-18-jsconf-summary-feature-team-and-developer-experience.pdf

**Comment by linesh-simplicity** [comment]
卧槽，直接出 pdf，太🐄了！！
