### ISSUE TITLE
技术专注

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#76]
技术的出现有着时代背景，当浪潮发现变化，投资也应当随机应变。

不合理的技术都不再耗费精力去学习了：
- Meteor：Universal JavaScript 在最初被提出时震惊世人，但真正应用起来却依然乏力，当通过 SSR （服务器端渲染）提高用户体验已成为公示的时候，技术依然服务于产品。[close #11]
- Vue 2.0：当 Vue 一再改进，变得越来越像 React 的时候，各大框架都早已区别不大。投资框架对于入门者来就像是初级程序员一再纠结编程语言的时候，进阶到某一阶段，语言早已没那么重要。 [close #20] 直接学习 TypeScript 也可以涵盖很多 ESNext 新特性。
- Angular 2.0：反观之 Angular，其企业级目标定位与工程化背景都是轻量级框架无法比拟的，但依然不适用于我自己。（参见 #31）[close #17]

对于技术细节来说，解决问题的能力才是更加看重的，ThoughtWorker 应当有虽未接触但能踏过障碍的自信心。而过早陷入细节是很危险的，因为坑的出现明明就是走向成功的非必要条件，若非**走过了**苦难才知忆苦思甜，那么其实苦难是没有价值的。（参见[苦难有什么价值？ - 知乎](https://www.zhihu.com/question/19988077)）

![image](https://s3.amazonaws.com/gitdoimages/20160917-2144623629.jpg)

**Comment by JimmyLv** [comment]
私以为如今值得投资学习的大概分为 Type System （TypeScript） + Functional view （React pure component, Elm） + Observable data（MobX, RxJS） + Realtime Database （Firebase） + Serverless （AWS Lambda）

**Comment by linesh-simplicity** [comment]
哈哈哈哈我勒个大*，你是写了脚本自动把聊天记录截成图片发表上来么！
😂😄😹😆🎭😅😌💀☺👌

🙏👆☝😇🙌⛪👼💒🙇➕

**Comment by JimmyLv** [comment]
我要做的事情还辣么多，何必纠结于这些技术本身？

**Comment by JimmyLv** [comment]
现如今已经选定了将 React 作为个人核心技术栈。

相关技术栈会体现在 [JimmyLv/demo.create-react-app-typescript: create-react-app, typescript, styled-components, dva(redux, redux-saga), ant-design http://dva.jimmylv.info](https://github.com/JimmyLv/demo.create-react-app-typescript)

Type System （TypeScript） => 好用！配合 Intellij #143 => 已切换至 Webstorm
Reactive Functional view （React pure component, Elm） => dva 完美的方案，期待 2.0 的分离
Observable data（MobX, RxJS） => dva 里面也有 subscription 的概念 + 当然还有 redux-saga 的运用
Realtime Database （Firebase） => 好用！Firebase 竟然没有在国内被墙，国内还可以用 Leancloud
Serverless （AWS Lambda） => 会被 cover 到 #30，2017 年会是 [serverless](https://github.com/serverless/serverless) 的爆发之年！

**Comment by linesh-simplicity** [comment]
就按照你这个 Guideline 混了啊~
