### ISSUE TITLE
Alfred Workflows 专题

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#78]
整理我日常使用的 Workflows：

- [x]先删除无用的，用得少的
- [x]确定分类
- [x]逐一阐述

### 加速输入

- Clipboard · 自带，剪切板历史 `Cmd + Shift + V`
- _* Snippets_ `+time` `+date` -> Dash 更加好用
- Copy URL · 快速 Markdown 链接 -> `url`
- md link for uploading image · Upload to 七牛 `Cmd + Ctrl + C`
- md link for searching text · `mdd {query}`, `mdg {query}`, `mdw {query}` 
- GitHub issues · `i {number}` goto the issue page, `⌘+⇧+i` open @ZenHub

### 系统辅助

- AirDrop · 直接打开 `airdrop`
- [manage-hidden-files](https://github.com/BubiDevs/manage-hidden-files) · toggle 隐藏文件 `hidden [true/false]`
- disable-shadow · toggle 截图时的阴影 `shadow [true/false]`
- Flux Control · `flux`
- Homebrew & Cask · `brew` `cask`
- Top Processes · `top`
- Kill Process · `kill {query}`
- Network · `wifi`
- Resize Image · `resize {query}`
- Restart App · `restart {query}`
- SizeUp · `size`
- Toggle Do Not Disturb · `notify`
- Toggle Fn keys as standard keys · `!fn`
- Uninstall with CleanMyMac 3 `uninstall {query}`
- Timer · `timer {interval}` 快速计时器

### 快捷查询

- APP Store · `app {query}` `mas {query}`
- Simple Folders Filter · 只打开文件夹 `f {query}`
- Chrome Bookmarks · `b {query}` -> Alfred 3.5 自带 Bookmarks
- Chrome History · `h {query}`
- Douban · `book {query}` `movie {query}`
- Emoji codes · `e {query}`
- Evernote · `ens {query}`
- Open urls with hotkey · 设置 Alfred 快捷键，一键打开 ZenHub Board `Cmd + Shift + I` `Cmd + Shift + Ctrl + I`
- tldr · `tldr {query}`
- Numi · `n {query}` 强大计算器
- npms · `npms {query}` 查询 NPM 包
- gist · `gist {query}` 搜索 GitHub Gist
- Google Suggest · `g {query}` 搜索建议，`gs {query}` 快速搜索 Index

### 编程相关

- npms · npms.io search `npms {query}`
- Font Awesome · `fa {query}`
- Dash · 查文档神器 `dash {query}` -> `js:array.in[xx]`
- GitHub Trending · `all`
- Launch Coding Related Apps · `coding`
- Open with Sublime Text · `subl {query}`
- JetBrains - Open project · `ws {query}`

### 集成服务

- Add to Instapaper · `ins {query}`
- GitHub · `gh {query}`

### Alfred 本身

- Fixum · Fix Alfred 3 workflows affected by the Sierra background process bug
- Packal Search · `packal workflows`
- Packal Updater · `packal`
- Workflow Searcher · `wf {query}`

## References

- [vitorgalvao/alfred-workflows: Collection of Alfred workflows](https://github.com/vitorgalvao/alfred-workflows)
- [learn-anything/alfred-workflows: 🎩 Amazing alfred workflows all can use to learn and do things faster](https://github.com/learn-anything/alfred-workflows)
- [Features Overview - Alfred Help and Support](https://www.alfredapp.com/help/overview/)

**Comment by JimmyLv** [comment]
除了 workflow 还有很多好用的功能！

- [Dynamic Placeholders - Alfred Help and Support](https://www.alfredapp.com/help/features/clipboard/dynamic-placeholders/)

![image](https://cloud.githubusercontent.com/assets/4997466/26148843/9c522f70-3b2a-11e7-937e-07d16037d43d.png)

**Comment by xiang578** [comment]
您好！能不能咨询一下在 `GitHub issues · i {number} goto the issue page, ⌘+⇧+i open @ZenHub`这一条中提到的 workflow 链接是什么？我在网上搜索了一下没有找到相关的workflow

**Comment by JimmyLv** [comment]
啊哈，这是最最基本的 Alfred Workflow 用法啦，自己在左下角新建一个就好啦。

![image](https://user-images.githubusercontent.com/4997466/35325355-71e25cb8-012e-11e8-8bf3-40af85736b78.png)

**Comment by xiang578** [comment]
感谢，这么一讲反应过来了，直接使用`web search`功能实现

**Comment by JimmyLv** [comment]
![](https://raw.githubusercontent.com/JimmyLv/images/master/2019/20190501205336.png)

Updated At 2019-05-01 8:51:42 PM
