### ISSUE TITLE
React UI 组件大集合

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#80]
排名不分先后：

- ![](https://www.google.com/s2/favicons?domain=ant.design) [Ant Design of React - Ant Design](http://ant.design/docs/react/introduce)
- ![](https://www.google.com/s2/favicons?domain=touchstonejs.io) [TouchstoneJS - React.js powered UI framework for developing beautiful hybrid mobile apps.](http://touchstonejs.io/)
- ![](https://www.google.com/s2/favicons?domain=elemental-ui.com) [Elemental UI](http://elemental-ui.com/)
- ![](https://www.google.com/s2/favicons?domain=rsuite.github.io) [RSuite | 一个基于 React.js 的 Web 组件库](http://rsuite.github.io/#/?_k=24qpzd)
- ![](https://www.google.com/s2/favicons?domain=www.material-ui.com) [Material-UI](http://www.material-ui.com/)
- ![](https://www.google.com/s2/favicons?domain=react-bootstrap.github.io) [React-Bootstrap](https://react-bootstrap.github.io/)
- ![](https://www.google.com/s2/favicons?domain=react.foundation) [React + Foundation · Foundation as React components](https://react.foundation/)
- ![](https://www.google.com/s2/favicons?domain=getessence.io) [Essence - React Material Design Framework](http://getessence.io/home)
- ![](https://www.google.com/s2/favicons?domain=tleunen.github.io) [React-MDL: React Components for Material Design Lite](https://tleunen.github.io/react-mdl/)
- ![](https://www.google.com/s2/favicons?domain=nikgraf.github.io) [Belle - Configurable React Components with great UX](http://nikgraf.github.io/belle/#/?_k=2o611w)
- ![](https://www.google.com/s2/favicons?domain=www.muicss.com) [MUI - Material Design CSS Framework](https://www.muicss.com/)
- ![](https://www.google.com/s2/favicons?domain=grommet.github.io) [Grommet](https://grommet.github.io/)
- ![](https://www.google.com/s2/favicons?domain=react-toolbox.com) [React Toolbox](http://react-toolbox.com/#/)
- ![](https://www.google.com/s2/favicons?domain=appcraft.github.io) [react-blazecss 0.4.3 Demo](https://appcraft.github.io/react-blazecss/)
- ![](https://www.google.com/s2/favicons?domain=styleguide.pivotal.io) [Pivotal UI: Intro](http://styleguide.pivotal.io/)
- ![](https://www.google.com/s2/favicons?domain=ui.baifendian.com) [BFD UI](http://ui.baifendian.com/)
- ![](https://www.google.com/s2/favicons?domain=semantic-ui.com/) [Semantic UI React](https://technologyadvice.github.io/stardust/introduction)
- ![](https://www.google.com/s2/favicons?domain=amazeui.org/) [Amaze UI React - Amaze UI components build with React](http://amazeui.org/react/)
- ![](https://www.google.com/s2/favicons?domain=blueprintjs.com/) [Blueprint – A React UI toolkit for the web](http://blueprintjs.com/)

归档至：

- [#Components · enaqx/awesome-react: A collection of awesome things regarding React ecosystem.](https://github.com/enaqx/awesome-react#components)
- [#Components · jondot/awesome-react-native: An "awesome" type curated list of React Native components, news, tools, and learning material](https://github.com/jondot/awesome-react-native#components)

鹅妹子嘤：

以后要找任何 UI 组件 都来这个网站 [JS.coach](https://js.coach/) 先搜索一下，简直太强大太完善！

> This is an opinionated catalog of open source JS packages.

![image](https://cloud.githubusercontent.com/assets/4997466/21712175/0c964802-d42e-11e6-9274-86f741f84b3f.png)

**Comment by laiyun1986** [comment]
赞一个。
我个人比较喜欢Semantic-UI，目前官方正在实现去jQuery化。
给你个地址：https://github.com/TechnologyAdvice/stardust

**Comment by JimmyLv** [comment]
@laiyun1986 棒棒的，我也喜欢 Semantic UI，只是不知道它有 React 版本，哈哈哈，谢谢推荐哈！

**Comment by Lucifier129** [comment]
我在用 Semantic-UI-React 做一个 side project，使用上很方便，但也有很多问题。其一是没有便利地按需引用的方式，不像 material-ui 那样方便。其二是 js + css 的体积太大了。

**Comment by bimohxh** [comment]
这里也有一个 React 专题  https://www.awesomes.cn/subject/react

**Comment by JimmyLv** [comment]
http://mp.weixin.qq.com/s?__biz=MjM5NzM0MjcyMQ==&mid=2650071570&idx=1&sn=9a59ba4736723887dad7a22f29c30255&chksm=bedb397c89acb06a19d06eb1713dd2922bd381882cc4de5a26383ff7f8eae5138cf7ab6f2cf5&mpshare=1&scene=1&srcid=0512oVnFSQVjrHBjnEjrGpo8#rd

**Comment by liangfei** [comment]
https://react.rocks/

**Comment by JimmyLv** [comment]
[React.js Examples](https://reactjsexample.com/)
