### ISSUE TITLE
🔆 Methodology | Personal Growth Infrastructure

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#88]
## 个人成长基础设施

- 硬件&软件篇 #121
- 常用代码（动态）模板 #41
- 常用脚手架 #122
- 可复用 UI 组件 #80 
- Intellij 相关配置 #60 与插件专题 #143 
- Alfred Workflow #78

## 已确定的不再折腾的东西

- 摄影类 Apps：[时光会走远，影像能长存。 -- XMind Online Library](https://www.xmind.net/m/TXMq)
- 知识管理类 Apps：Instapaper、Diigo、XMind
- 效率类 Apps：滴答清单、Pomotodo、潮汐
- 编程类：Intellij -> Webstorm、Dash
- React 技术栈：TypeScript、styled-components、dva、ant.design

**Comment by linesh-simplicity** [comment]
nicejob。原本想法是说，使用 brew/cask/appstore/chrome extenstion 的层级先把 app 管理起来，再用脚本把 brew/cask/appstore 的安装自动化起来。然后，重新装机只需要：

```bash
apps install 
```

**Comment by JimmyLv** [comment]
@linesh-simplicity 得益于 Unix 的文件系统设计，其实好像只需要把 Applications 和 /usr/local/bin/ 整个目录拷贝一下？

**Comment by linesh-simplicity** [comment]
@JimmyLv hopefully ... 感觉会有坑
