### ISSUE TITLE
（追求）完美的 GitHub Issues 体验

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#93]
> 还是从需求出发，理想很美好，但是现实往往也不是那么如意...

## 美好的一面

- `#!` 直接新建 issue

![image](https://cloud.githubusercontent.com/assets/4997466/20562802/87b398d6-b1c0-11e6-860b-c14649d6b696.png)

### 一些限制

- [x] 比如网络，ZenHub 在国内（非公司网络）哪怕 XX-Net 翻墙的情况下都无法访问，原因大概是因为使用了非 HTTP 的网络协议。 => 开 VPN，配置一键自动化脚本
- [ ] 还有同步的速度问题，印象笔记和 Evernote 的不同，以及其他国外产品的不实时。其实身处番茄当中，真正专注的时候才发现时间会浪费在哪里，因为以往情况下一旦网络不好就很有可能去做其他事情而一去不复返了。 => 只能是多在公司呆着吧。
- [x] 时不时来点小 Bug，比如印象笔记的展示功能对于 inline code 硬是无缘无故换了个行，原本美观的印象就如滔滔江水把美梦给拍没了。=> 这个功能还是太少用了，放到印象笔记里的东西连看不会看，更何况好看不好看呢。
- [x] 学习成本，就如 Gitlo，搞了半天才知道它只会同步 Trello 中新创建的 Card，而且还不能实现很好的双向同步，GitHub Issue 改了标题但是 Trello 中不会改，Trello 中有自己的 checklist 但是 GitHub Issue 原生支持 `\\\\- [x]` TODO 列表语法，并且还能拖动！ => 已经弃用 Gitlo #92 

![image](https://cloud.githubusercontent.com/assets/4997466/20562818/99e82d8c-b1c0-11e6-8640-c45f7d4ab0da.png)

### 再谈需求

- [x] **ZenHub 打开无能**：在公司无须解决，但是大部分 Personal Work 大概都在家里啊。必须开 VPN 是一件很蛋疼很费网速的事儿，但是考虑到现在上的大部分网站都是国外的，那就还不如每次都全线 VPN 翻墙算了。
  - [x] 反正最近 XX-Net 真心不太好用，换 VPN 的话要配一下自动登录的脚本。
  - [x] 做个 VPN vs XX-Net 网速测试，下载被墙的资源和墙外非墙资源。 => 没啥意义，国内网站依然挺快的，下载东西的时间也毕竟很少。
- [x] **刷 GitHub 提交**：方便快捷 Create Issue，手机端的操作依旧还是少数吧，所以是否可以通过 IFTTT 的 Do 应用来快速提交一个 Issue。 => 用上了 GitDo 这个很好用的 App => 最近下架了是什么鬼！！！！
- [x] **管理 Issues**：最好用的当然就是 Pipeline，即一面故事墙，而且 ZenHub 还可以创建 Epic 再添加其他的 Issues，Issue 里面还可以添加 Checklist，所以就有了完美的三层结构。 ~~之前考虑的Gitlo可以把每个 Issue 的进程和 Trello 的实时效果很棒，Web 端和手机端都非常流畅顺滑。~~ => 绕来绕去依然选用了 ZenHub。
- [x] **直接在 GitHub 中查看 Pipeline**：要满足这个需求，目前来说最好用的就是 ZenHub ，也许有同类产品但由于切换成本就不会再轻易迁移过去了。=> 绕来绕去依然选用了 ZenHub。 +1
- [x] **快捷键的支持**：GitHub 的快捷键非常贴心，而 ZenHub 的快捷键则延续设计完全没有违和感。 => 配合 vim 插件的 insert 模式，没有快捷键操作不了的事情！
- [x] **快速打开，新建**：使用 Alfred 和 Sublime 的插件输入命令一键打开。 => 把 GitHub issue 地址加入书签，在 Chrome 的地址栏里输入关键词就可以一触即达了。

### 所以还是要设立一些原则

- 减少第三方：间接地通过 Gitlo 来使用 Trello 其实就增加了不稳定性，鬼知道 Gitlo 这样一个小众产品哪天就挂了呢？其实 Trello 的使用习惯我还没能
- 减少切换成本：ZenHub 就无缝嵌入在 GitHub 页面里边儿，而 Trello 则需要打开另外一个页面。
- 减少识别成本：使用 Issues 的 label 对应 Trello 里面的 list，而 Trello 却还有自己的 label，这显然增加了识别困难。若只是把 Trello 当成展示工具未免大材小用了，而 Issues 的 label 本应该拿来做标签本身的事情，不应被简单充当了 list name 而已。
- 减少学习成本：最简单的例子就是，已经掌握了 GitHub 的快捷键就不会再想记一遍 Trello 的快捷键了。

### 调研与最佳实践

* 移动端： 
  * 发现了好多 GitHub Issue 的 App，然后也可以手动使用 IFTTT 新建一个，但是只能 Create 不能修改却很恼火啊。
  * 于是找到比较完美的一个 App：[GitDo](http://gitdo.io/)，还附赠了移动端的 Pipeline，相当于一个 ToDo List。
  * 而且，GitDo 这哥们也会在 Issue 里面新加一个 Label，既然如此，那就统一一下标签，彻底排除 Trello。
  
![image](https://cloud.githubusercontent.com/assets/4997466/20562832/b1916908-b1c0-11e6-9961-cb5d65ab893a.png)

* 电脑端：
  * 题外话：可能自己又会重新爱上印象笔记的富文本编辑吧，实时的样式和图片预览以及图片的大小拖拽，还有完美的快捷键都让人心旷神怡。
  * 把 GitHub issues 的地址加入书签过后，当然要结合 Alfred #78  的书签插件：
  * 结合 Sublime 及其插件 
    * `Cmd + Ctrl + P` 打开对应的 project
    * 然后 `Cmd + Shift + P` 打开 `Create/Open issue`

![](http://7xjbdq.com1.z0.glb.clouddn.com/images/2016/1480222795873.png)

* Rethink 闭环系统：想想 Kindle 如何集成到整套系统当中来？
  * Kindle 还有 iOS 版，不得不说阅读体验也是相当得赞，而且可以与 Kindle Paperwhite 同步。 
    * 既然可以多设备同步，所以不同设备的接收邮箱地址不同也没什么影响了。
    * 所以之前所设置的 Pocket 每日三篇就又可以开始阅读了，而且没有任何场地限制，[ ] 笔记也可以导出？待确认。
  * 与此同时，借鉴于这种方法，最核心的理念就是每日循环 + 邮件发送，很容易实现。 
    * 甚至印象笔记也可以[直接发送到 Kindle](http://en2kindle.com/yinxiang/)，或者直接发送到 [460051518_34@kindle.cn](mailto:460051518_34@kindle.cn)。
    * [如何实现将印象笔记中的笔记直接发送到 Pocket](https://getpocket.com/emails)，加标签然后 IFTTT/先发送到 Evernote 生成 public link 再发送到 [add@getpocket.com](mailto:add@getpocket.com)，~~然后再设置注册 Pocket 的邮箱自动转发至 [add@getpocket.com](mailto:add@getpocket.com)（Pocket 只能识别单一 link，不能存储整篇文章）。~~ => 已经弃用 Pocket 和印象笔记。 => 采用 Instapaper 和 Diigo #28

**Comment by JimmyLv** [comment]
最终方案简要如下：

- （快速）打开：Alfred + b / Chrome 书签
- （方便）管理：采用 ZenHub （Epic & Pipeline & ...）
- 移动端：由于 GitDo 的下架，暂时没有比较好的解决方案 => 改用 @滴答清单 来撑撑场面和同步（语音输入）内容。

**Comment by JimmyLv** [comment]
2018 年 updated:

- Ship：本来都在用 [Ship](https://www.realartists.com/blog/ship-20.html) macOS 原生客户端，用得好好的结果它因为 Business 就要关闭服务器了，😔
- ZenHub：[ZenHub](https://app.zenhub.com/workspace/o/jimmylv/jimmylv.github.io/boards?repos=13273392) 的打开速度太慢，特别是相对于 GitHub 的 [Project](https://github.com/JimmyLv/jimmylv.github.io/projects/1?fullscreen=true) 来说。 => 差点放弃，1. 本来 Ship 里面直接支持创建和打开 GitHub Project（且自动fullscreen）2. Zenhub 可以pin 在Chrome里面，所以打开速度倒也无妨。
- GitHawk：mobile 端就是在用开源的 [GitHawk](https://github.com/GitHawkApp/GitHawk)，真心不错的，可以 bookmark 常打开的几个issues，随时记录想法。

系统性思维，唯一有用的方式是打造闭环，且完整：

![eric rise](https://user-images.githubusercontent.com/4997466/42457384-f1155314-83c9-11e8-9b23-2463d61c2100.jpeg)

1. 节奏：一定要平衡，周期性！（两周 or 一个月 or 每个月的第一个周末）
2. 透明：对自己诚实，列Tasking，无预则废
3. 反馈：反馈从何而来，review！即 Measure


![jonnyschneider_diagram_artboard203_125ff10e0a26d24871eab89d01cd0477](https://user-images.githubusercontent.com/4997466/42457355-e29d64fc-83c9-11e8-91d8-55152b82ab44.png)

**Comment by linesh-simplicity** [comment]
盗图盗图。最后一图简直太好。只在 Agile 的范围内讨论问题是没有衡量标准的哟~没有 LEAN 很可能就高效地做了个破烂出来哟~
