### ISSUE TITLE
如何对时间进行分类？

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#96]
### 下一个难题便是「如何对时间进行分类？」

> 看到这篇标题党般的文章 [全球唯一柳比歇夫时间日志法完整版 | 知行合一的自我管理博客-知行会](http://www.zhixinghui.org/blog/?p=503) 实在是有点儿受不了，故对自己的时间分类学做了更为详细的分析和说明，与君共勉！

**'睡眠 基本 浪费 目标(>1)'** 这才是于我而言更好的分类：

1. 首先我并不认同把时间作为投资学的一种成本，实在是太功利太浮夸甚至太奢侈，且不说充满着铜臭味般的意味，还会让人产生一种时间就像金钱一样可以增值可以挣回来一般的错觉？
2. 如《奇特的一生》当中所言，我依然对时间充满敬畏之心，且最好的方式都只能奢求时间能够跟自己做朋友，伴随着一生共同成长而不只是单纯的利用关系。
3. 睡眠占去 1/3，此生只剩 2/3，除去非做不可的[基本生活维护成本](http://blog.jimmylv.info/2015-09-05-periodically-anxiety/#title0)过后，剩下的时间要么选择浪费而荒度此生，要么选择目标而奋力向前，让这一生不留遗憾。
4. 关注点当然在于目标的如何实现以及实现的效率如何，所以需要进一步的细化，每一个目标的执行都值得被记录和分析，而其他睡眠和基本时间则随之而去吧~
5. 在目标的具体分类当中，**职业、工作**一定是我想做的事情，并不是单纯为了生存而已；**沟通、学习和技能**的提升必然是为了更好的生活，以及更好地完成目标，剩下的时间并不如想象中那么多；**技术、编程和产品**是为了做一个更好的程序员，而**阅读、思考、写作**则是为了内心的丰富，在持续回顾与自省的与此同时，分享知识以回馈价值的流通性；**休闲、运动、旅行/摄影（with 朋友、家人）**，这几乎就是最终形态的幸福。

![image](https://cloud.githubusercontent.com/assets/4997466/20489562/0051f426-b046-11e6-8304-96bc35b75143.png)

![image](https://cloud.githubusercontent.com/assets/4997466/20490839/431d2128-b04a-11e6-9035-744f97363d16.png)

**Comment by JimmyLv** [comment]
依然会有痛点：

- [ ] 中文难以输入，特别是在 Mobile 上 => 改成全英文
- [ ] 详细程度有待商榷，在电脑上很容易通过网页集成开始具体项目，但依然还有一些事务模糊不清 => Just Working
- [ ] #97 如何使用标签系统？ => 比如说 Meetings，可以添加不同的 description 或者 tags， 即 Tech-Huddle Meeting vs Meetings(with 'Tech-Huddle' Tags)

**Comment by JimmyLv** [comment]
对 Toggl 的第一次优化完毕。

**Comment by linesh-simplicity** [comment]
把 #IPM 或 #Tech-Huddle 作为 TAG 写在 description 字段中的话，如何被Toggl 统计呢？可有更新？

听 Showcase 中。。。

**Comment by JimmyLv** [comment]
只要在 Summary 里面搜索 keyword `#Tech-Huddle` 即可

**Comment by JimmyLv** [comment]
后续改成了$符号，意味着开会就是钱，而且是客户给钱。

**Comment by JimmyLv** [comment]
其实我貌似错怪了时间投资学那本书，书的内容不错，而且只有一部分内容是讲的分类。

**Comment by forrestchang** [comment]
说一下我用 Toggl 的分类，这套系统我用了好几年了，可以从 https://sspai.com/post/43363 看到最开始的一些设置，现在已经优化了很多。

总体分成三个层次：领域 - 子领域 - 项目

例如：Work - Open Source - 完成开源项目xxxx

记录的最小维度为 Project，这样可以保证生成报表的可控，不属于某个 Project 的记录可以放到某个 Misc 项目中。

参考了你这边使用 GitHub Issue 记录每个 Project 的设定，以后可以直接在 Issue 上记录时间了。
